;(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    define('cfxnes', [], function() {
      return factory({}).cfxnes;
    });
  } else if (typeof module === 'object' && module.exports) {
    module.exports = factory({}).cfxnes;
  } else {
    factory(root);
  }
}(this, function(root) {
  // Compiler output [start]
  'use strict';var c,aa='function'==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)},ba='undefined'!=typeof window&&window===this?this:'undefined'!=typeof global&&null!=global?global:this;function ca(){ca=function(){};ba.Symbol||(ba.Symbol=da)}var da=function(){var a=0;return function(b){return'jscomp_symbol_'+(b||'')+a++}}();
function ea(){ca();var a=ba.Symbol.iterator;a||(a=ba.Symbol.iterator=ba.Symbol('iterator'));'function'!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return fa(this)}});ea=function(){}}function fa(a){var b=0;return ha(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function ha(a){ea();a={next:a};a[ba.Symbol.iterator]=function(){return this};return a}function e(a){ea();ca();ea();var b=a[Symbol.iterator];return b?b.call(a):fa(a)}
function ia(a){for(var b,d=[];!(b=a.next()).done;)d.push(b.value);return d}var ja='function'==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ka;if('function'==typeof Object.setPrototypeOf)ka=Object.setPrototypeOf;else{var la;a:{var ma={Yd:!0},na={};try{na.__proto__=ma;la=na.Yd;break a}catch(a){}la=!1}ka=la?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+' is not extensible');return a}:null}var oa=ka;
function g(a,b){a.prototype=ja(b.prototype);a.prototype.constructor=a;if(oa)oa(a,b);else for(var d in b)if('prototype'!=d)if(Object.defineProperties){var f=Object.getOwnPropertyDescriptor(b,d);f&&Object.defineProperty(a,d,f)}else a[d]=b[d];a.oe=b.prototype}function pa(a){return a instanceof Array?a:ia(e(a))};function k(a){if('number'===typeof a)return 1024>Math.abs(a)?a+' B':1048576>Math.abs(a)?~~(a/1024*1E3)/1E3+' KB':~~(a/1048576*1E3)/1E3+' MB'}function n(a){var b=typeof a;if('string'===b)return 80<a.length?'"'+a.substr(0,80)+'..."':'"'+a+'"';if('function'===b)return b=qa(a.constructor),(a=qa(a))?b+'('+a+')':b;if(a&&'object'===b){b=qa(a.constructor);if('Object'===b)return b;a=a.length;return null!=a?b+'('+a+')':b}return String(a)}var ra=/function ([^(]+)/;
function qa(a){return a.name?a.name:(a=a.toString().match(ra))&&a[1]?a[1]:''};var sa={},ta=(sa.S0=[0,0,0,0],sa.S1=[1,1,1,1],sa.S2=[2,2,2,2],sa.S3=[3,3,3,3],sa.H=[0,0,1,1],sa.V=[0,1,0,1],sa['4S']=[0,1,2,3],sa);var ua={pc:60,$d:1789773,Xc:!0,kb:[7457,7456,7458,7457,1,1],lb:[7457,7456,7458,7458,7452,1],Tc:[4,8,16,32,64,96,128,160,202,254,380,508,762,1016,2034,4068],Hc:[428,380,340,320,286,254,226,214,190,160,142,128,106,84,72,54]},va={pc:50,$d:1491477.5,Xc:!1,kb:[8313,8314,8312,8313,1,1],lb:[8313,8314,8312,8314,8312,1],Tc:[4,8,14,30,60,88,118,148,188,236,354,472,708,944,1890,3778],Hc:[398,354,316,298,276,236,210,198,176,148,132,118,98,78,66,50]};
function wa(a){switch(a){case 'NTSC':return ua;case 'PAL':return va;default:throw Error('Invalid region: '+n(a));}};var xa={},ya=(xa.off=0,xa.error=1,xa.warn=2,xa.info=3,xa);function za(){this.f=console;this.c=0;this.g='off'}za.prototype.h=function(a){var b=ya[a];if(null==b)throw Error('Invalid log level: '+n(a));this.c=b;this.g=a};za.prototype.i=function(){return this.g};za.prototype.error=function(a,b){1<=this.c&&this.f.error(a,b)};function Aa(a){var b=y;2<=b.c&&b.f.warn(a)}function A(a){var b=y;3<=b.c&&b.f.info(a)}var y=new za;function Ba(){A('Initializing CPU memory');this.g=new Uint8Array(2048);this.ka=this.Ra=null;this.sc=new Uint32Array(4);this.Pb=0;this.c=[null,null,null];this.f=0;this.N=this.ca=this.o=this.u=null}c=Ba.prototype;c.connect=function(a){A('Connecting CPU memory');this.u=a.u;this.o=a.o;this.ca=a.ca};c.Aa=function(a){this.ka=(this.N=a)&&a.ka;this.Ra=a&&a.Ra};c.reset=function(){A('Resetting CPU memory');this.g.fill(0);this.Pb=this.f=0;this.sc.fill(0)};
c.read=function(a){return 32768<=a?this.Ra[this.sc[(a&24576)>>>13]|a&8191]:8192>a?this.g[a&2047]:16416>a?Ca(this,a):24576<=a?this.ka&&this.N.ic?this.ka[this.Pb|a&8191]:0:0};
c.write=function(a,b){if(32768<=a)this.N.write(a,b);else if(8192>a)this.g[a&2047]=b;else if(16416>a)switch(16384>a?a&8199:a){case 8192:a=this.u;var d=a.ub;Da(a,b);a.g=a.g&62463|(b&3)<<10;!a.na||d||!a.ub||a.f&524288||(a.R=1);break;case 8193:a=this.u;Ea(a,b);a.ua=a.zb[a.Wb];break;case 8195:this.u.Pa=b;break;case 8196:a=this.u;!a.Fb&&(a.ma||a.v)||(a.l[a.Pa]=b);a.Pa=a.Pa+1&255;break;case 8197:a=this.u;a.s=!a.s;a.s?(a.L=b&7,a.g=a.g&65504|b>>>3):a.g=a.g&3103|(b&248)<<2|(b&7)<<12;break;case 8198:this.u.Bc(b);
break;case 8199:a=this.u;!a.Fb&&(a.ma||a.v)||a.C.write(a.c,b);Fa(a);break;case 16404:this.ca.Bc(b);break;case 16406:Ga(this,b);break;case 16384:Ha(this.o.ea,b);break;case 16385:Ia(this.o.ea,b);break;case 16386:this.o.ea.qa(b);break;case 16387:this.o.ea.pa(b);break;case 16388:Ha(this.o.fa,b);break;case 16389:Ia(this.o.fa,b);break;case 16390:this.o.fa.qa(b);break;case 16391:this.o.fa.pa(b);break;case 16392:Ja(this.o.ha,b);break;case 16394:this.o.ha.qa(b);break;case 16395:this.o.ha.pa(b);break;case 16396:Ka(this.o.da,
b);break;case 16398:this.o.da.qa(b);break;case 16399:this.o.da.pa(b);break;case 16400:La(this.o.Y,b);break;case 16401:this.o.Y.c=b&127;break;case 16402:this.o.Y.m=49152|(b&255)<<6;break;case 16403:this.o.Y.s=(b&255)<<4|1;break;case 16405:a=this.o;d=a.ea;var f=0!==(b&1);f||(d.f=0);d.l=f;d=a.fa;f=0!==(b&2);f||(d.f=0);d.l=f;d=a.ha;f=0!==(b&4);f||(d.c=0);d.i=f;d=a.da;f=0!==(b&8);f||(d.c=0);d.j=f;Ma(a.Y,0!==(b&16));break;case 16407:Na(this.o,b),Ga(this,b)}else 24576<=a&&this.ka&&this.N.jc&&(this.ka[this.Pb|
a&8191]=b,this.N.Mc&&this.N.write(a,b))};function Ca(a,b){switch(16384>b?b&8199:b){case 8194:return a.u.uc();case 8196:return a=a.u,b=a.l[a.Pa],2===(a.Pa&3)&&(b&=227),b;case 8199:return a=a.u,16128===(a.c&16128)?(b=a.C.read(a.c),a.Hb=a.C.read(a.c&12287)):(b=a.Hb,a.Hb=a.C.read(a.c)),Fa(a),a=b,a;case 16405:return a.o.uc();case 16406:return Oa(a,1);case 16407:return Oa(a,2);default:return 0}}
c.xc=function(a,b){A((null!=b?'Setting':'Clearing')+' device connected to CPU memory on port #'+a);this.c[a]=b};c.Lb=function(a){return this.c[a]};function Oa(a,b){return(a=a.c[b])?a.read():0}function Ga(a,b){if((b&=1)&&!a.f){var d=a.c[1];d&&d.zc();(d=a.c[2])&&d.zc()}a.f=b};var Pa=[9,1,0,1,0,2,2,13,8,16,8,36,0,0,4,44,9,1,52,3,0,4,0,20,8,58,0,2,0,32,44,8];function Qa(){A('Initializing PPU memory');this.g=null;this.Nb=new Uint32Array(8);this.h=!1;this.c=new Uint8Array(4096);this.f=new Uint32Array(4);this.Ya=new Uint8Array(32);this.N=null}Qa.prototype.Aa=function(a){this.g=(this.N=a)&&(a.La||a.ib);this.h=null!=a&&null!=a.La};Qa.prototype.reset=function(){A('Resetting PPU memory');this.Nb.fill(0);this.c.fill(0);Ra(this,this.N&&this.N.nb||'S0');this.Ya.set(Pa)};
Qa.prototype.read=function(a){a&=16383;return 8192>a?Sa(this,a):16128>a?Ta(this,a):this.Ya[Ua(a)]};Qa.prototype.write=function(a,b){a&=16383;8192>a?this.h&&(this.g[this.Nb[(a&7168)>>>10]|a&1023]=b):16128>a?this.c[this.f[(a&3072)>>>10]|a&1023]=b:this.Ya[Ua(a)]=b};function Sa(a,b){return a.g[a.Nb[(b&7168)>>>10]|b&1023]}function Ta(a,b){return a.c[a.f[(b&3072)>>>10]|b&1023]}function Ra(a,b){var d=ta[b];if(!d)throw Error('Invalid mirroring: '+n(b));b=d;for(d=0;4>d;d++)a.f[d]=1024*b[d]}
function Ua(a){return a&3?a&31:a&15};function Va(){A('Initializing DMA');this.f=this.c=0;this.A=null}c=Va.prototype;c.connect=function(a){A('Connecting DMA');this.A=a.A};c.reset=function(){A('Resetting DMA');this.c=512};c.Bc=function(a){this.c=0;this.f=a<<8};c.w=function(){if(this.Mb()&&(this.c++,this.c&1)){var a=this.A.read(this.f+(this.c>>1));this.A.write(8196,a)}};c.Mb=function(){return 512>this.c};function B(a){A('Initializing mapper');this.nb=a.nb;this.Ra=a.Ra;this.ib=a.ib;this.ya=a.ya;this.Va=a.Va;var b=a.ob,d=a.Qb;this.ka=b?new Uint8Array(b):null;this.ob=b;this.Qb=d;this.ic=0<b;this.jc=0<b;this.Mc=!1;b=a.hb;a=a.Jb;this.La=b?new Uint8Array(b):null;this.hb=b;this.Jb=a;d?this.l=this.ka.subarray(0,d):a?this.l=this.La.subarray(0,a):this.l=null;this.C=this.A=this.u=this.K=null}c=B.prototype;
c.connect=function(a){A('Connecting mapper');this.K=a.K;this.u=a.u;this.A=a.A;this.C=a.C;this.K.Aa(this);this.A.Aa(this);this.C.Aa(this)};c.disconnect=function(){A('Disconnecting mapper');this.C.Aa(null);this.A.Aa(null);this.K.Aa(null);this.K=this.u=this.A=this.C=null};c.reset=function(){A('Resetting mapper');this.ka&&this.ka.fill(0,this.Qb);this.La&&this.La.fill(0,this.Jb);this.ia()};c.ia=function(){};c.write=function(){};c.w=function(){};function Wa(a,b){Xa(a,0,4*b,4)}
function D(a,b,d){Xa(a,2*b,2*d,2)}function Xa(a,b,d,f){f=void 0===f?1:f;for(var h=a.ya-1>>13,l=0;l<f;l++)a.A.sc[b+l]=8192*(d+l&h)}function Ya(a,b){a.A.Pb=8192*(b&a.ob-1>>13)}function E(a,b){Za(a,0,8*b,8)}function Za(a,b,d,f){f=void 0===f?1:f;for(var h=(a.Va||a.hb)-1>>10,l=0;l<f;l++)a.C.Nb[b+l]=1024*(d+l&h)}c.qc=function(){return this.l};function $a(a,b){Ra(a.C,'S'+(void 0===b?0:b))};function ab(a){B.apply(this,arguments)}g(ab,B);ab.prototype.ia=function(){Wa(this,0);E(this,0)};ab.prototype.write=function(a,b){Wa(this,b);$a(this,(b&16)>>>4)};function bb(a){B.apply(this,arguments)}g(bb,B);bb.prototype.ia=function(){Wa(this,0);E(this,0)};bb.prototype.write=function(a,b){Wa(this,b)};function cb(a){B.apply(this,arguments)}g(cb,B);cb.prototype.ia=function(){D(this,0,0);D(this,1,-1);E(this,0)};cb.prototype.write=function(a,b){E(this,b)};function db(a){B.apply(this,arguments)}g(db,B);db.prototype.ia=function(){Wa(this,0);E(this,0)};db.prototype.write=function(a,b){Wa(this,b);E(this,b>>>4)};function eb(a){B.call(this,a);this.j=this.f=this.i=this.g=this.h=this.c=0;this.m=(131072===this.ya||262144===this.ya)&&8192===this.ob&&(8192===this.Va||8192===this.hb)}g(eb,B);eb.prototype.ia=function(){this.h=this.c=0;this.g=12;this.j=this.f=this.i=0;fb(this);gb(this);hb(this);ib(this)};
eb.prototype.write=function(a,b){if(b&128)this.h=this.c=0,this.g|=12;else if(this.c|=(b&1)<<this.h,5<=++this.h){switch(a&57344){case 32768:this.g=this.c;break;case 40960:this.f=this.c;break;case 49152:this.j=this.c;break;case 57344:this.i=this.c}this.h=this.c=0;fb(this);gb(this);hb(this);ib(this)}};function fb(a){switch(a.g&3){case 0:$a(a,0);break;case 1:$a(a,1);break;case 2:Ra(a.C,'V');break;case 3:Ra(a.C,'H')}}
function gb(a){var b=a.La?a.f&16:0,d=a.i&15;switch(a.g&12){case 12:D(a,0,b|d);D(a,1,b|15);break;case 8:D(a,0,b);D(a,1,b|d);break;default:Wa(a,(b|d)>>>1)}}function hb(a){var b=0===(a.f&16);b=0===(a.i&16)&&(!a.m||b);Ya(a,a.La?a.f>>>2:0);a.ic=b;a.jc=b}function ib(a){a.g&16?(Za(a,0,4*a.f,4),Za(a,4,4*a.j,4)):E(a,a.f>>>1)};function jb(a){B.call(this,a);this.g=this.h=this.j=this.i=this.f=this.c=0}g(jb,B);jb.prototype.ia=function(){D(this,0,0);D(this,1,-1);Ya(this,0);E(this,0);this.g=this.h=this.j=this.i=this.f=this.c=0};
jb.prototype.write=function(a,b){switch(a&57345){case 32768:this.c=b;break;case 32769:switch(this.c&7){case 0:case 1:Za(this,2*((this.c&128)>>>6|this.c&1),2*(b>>>1),2);break;case 2:case 3:case 4:case 5:Za(this,(~this.c&128)>>>5|this.c-2&3,b);break;case 6:a=(~this.c&64)>>>5;Xa(this,(this.c&64)>>>5,b);Xa(this,a,-2);break;case 7:Xa(this,1,b)}break;case 40960:'4S'!==this.nb&&(b&1?Ra(this.C,'H'):Ra(this.C,'V'));break;case 40961:this.ic=128===(b&128);this.jc=128===(b&192);break;case 49152:this.i=b;break;
case 49153:this.f=0;break;case 57344:this.h=!1;kb(this.K,16);break;case 57345:this.h=!0}};jb.prototype.w=function(){if(this.u.U&4096){if(!this.g){!this.f||this.j?this.f=this.i:this.f--;if(this.h&&!this.f){var a=this.K;a.g|=16}this.j=!1}this.g=7}else this.g&&this.g--};function lb(a){B.call(this,a);this.Mc=!0}g(lb,B);lb.prototype.ia=function(){Wa(this,0);Ya(this,0);E(this,0)};lb.prototype.write=function(a,b){switch(a){case 32765:Wa(this,b);break;case 32766:Za(this,0,4*b,4);break;case 32767:Za(this,4,4*b,4)}};function mb(a){B.apply(this,arguments)}g(mb,B);mb.prototype.ia=function(){D(this,0,0);D(this,1,-1);E(this,0)};function nb(a){B.apply(this,arguments)}g(nb,B);nb.prototype.ia=function(){D(this,0,0);D(this,1,-1);E(this,0)};nb.prototype.write=function(a,b){D(this,0,b)};var F={},ob=(F.AOROM=ab,F.BNROM=bb,F.CNROM=cb,F.COLOR_DREAMS=db,F.MMC1=eb,F.MMC3=jb,F.NINA_001=lb,F.NROM=mb,F.UNROM=nb,F);var pb='LE'===(52===(new Uint8Array((new Uint16Array([4660])).buffer))[0]?'LE':'BE'),sb=pb?qb:rb,vb=pb?tb:ub,wb=sb(0,0,0);function qb(a,b,d,f){return((void 0===f?255:f)<<24|d<<16|b<<8|a)>>>0}function rb(a,b,d,f){return(a<<24|b<<16|d<<8|(void 0===f?255:f))>>>0}function tb(a){return[a&255,a>>>8&255,a>>>16&255,a>>>24&255]}function ub(a){return[a>>>24&255,a>>>16&255,a>>>8&255,a&255]};var xb={'asq-real-a':'YGBgACF7AACcMQCLWQBvbwAxZAAATxEALxkAJykAAEQAADk3ADlPAAAADAwMDAwMrq6uEFbOGyz/YCDsqQC/yhZUyhoInjoEZ1EAQ2EAAHwAAHFTAHGHDAwMDAwMDAwM////RJ7+XGz/mWb/12D//2KV/2RT9JQwwqwAkMQUUtIoIMaSGLrSTExMDAwMDAwM////o8z/pLT/wbb/4Lf//8DF/7yr/9Cf/OCQ4uqYyvKgoOrioOL6tra2DAwMDAwM','asq-real-b':'bGxsACCUAACoPACYcABwfAA8cAAAaBAARhoAPCwAAFAAADxMADpmAAAAEBAQEBAQurq6KljWPDL/gCDwwADA0BR00hokpjweflIAWGQAAIgAAHRoAHKeEBAQEBAQEBAQ////XqD/jIL/xHD//1z//2i8/3J8/JZK2a0AmMYuTtROOsiaLr7cWFhYEBAQEBAQ////xtj/1Mr/8MT//7z//8Tw/8rU/9i+/+am6uyyxvTGuuzqtub/wsLCEBAQEBAQ',
'bmf-fin-r2':'UlJSAACACACKLAB+SgBOUAAGRAAAJggACiAAAC4AADIAACYKABxIAAAAAAAAAAAApKSkADjONBbsXgTcjACwmgBMkBgAcDYATFQADmwAAHQAAGwsAF6EAAAAAAAAAAAA////TJz/fHj/pmT/2lr/8FTA8GpW1oYQuqQAdsAARswaLshmNMK+Ojo6AAAAAAAA////ttr/yMr/2sL/8L7//Lzu+sLA8syi5tqSzOaOuO6iruq+rujisLCwAAAAAAAA','bmf-fin-r3':'aGhoABKZGgiqUQKafgBpjgAcfgMBURgAHzcAAU4AAFoAAFAcAEBhAAAAAAAAAAAAubm5DFzXUDXwiRnguwyzzgxhwCsOlU0BYW8AH4sAAZgMAJNLAIGbAAAAAAAAAAAA////Y7T/m5H/03f/72r/+WjA+X1s7Zstvb0WfNocS+hHNeWRP9ndYGBgAAAAAAAA////rOf/1c3/7br/+LD//rDs/b21+dKO6Ot8u/OCmfeiivXQkvTxvr6+AAAAAAAA',
'fceu-13':'YGBgAAB4FACALABuSgBObAAYWgMCURgANCQAADQAADIAADQgACx4AAAAAgICAgICxMTEAFjeMB/8fxTgqACwwAZcwCsOpkAQb2EAMIAAAHwAAHw8AG6EFBQUBAQEBAQE8PDwTKr/b3P1sHD/2lr/8GDA+INt0JAw1MAwZtAAJt0aLshmNMK+VFRUBgYGBgYG////ttr/yMr/2sL/8L7//Lzu/9C0/9qQ7OyS3PaeuP+iruq+nu/vvr6+CAgICAgI','fceu-15':'YGBgAABwFACALABuSgBObAAYWgMCURgANCQAADQAADIAADQgACx4AAAAAgICAgICxMTEAFjeMB/8fxTgqACwwAZcwCsOpkAQb2EAMIAAAHwAAHw8AG6EFBQUBAQEBAQE8PDwTKr/b3P1sHD/2lr/8GDA+INt0JAw1MAwZtAAJt0aLshmNMK+VFRUBgYGBgYG////ttr/yMr/2sL/8L7//Lzu/9C0/9qQ7OyS3PaeuP+iruq+nu/vvr6+CAgICAgI',
fceux:'dHR0JBiMAACoRACcjAB0qAAQpAAAfAgAQCwAAEQAAFAAADwUGDxcAAAAAAAAAAAAvLy8AHDsIDjsgADwvAC85ABY2CgAyEwMiHAAAJQAAKgAAJA4AICIAAAAAAAAAAAA/Pz8PLz8XJT8zIj89Hj8/HS0/HRg/Jg48Lw8gNAQTNxIWPiYAOjYeHh4AAAAAAAA/Pz8qOT8xNT81Mj8/MT8/MTY/Lyw/Nio/OSg4PygqPC8sPzMnPzwxMTEAAAAAAAA','nestopia-rgb':'bW1tACSSAADbbUnbkgBttgBttiQAkkkAbUkAJEkAAG0kAJIAAElJAAAAAAAAAAAAtra2AG3bAEn/kgD/tgD//wCS/wAA220Akm0AJJIAAJIAALZtAJKSJCQkAAAAAAAA////bbb/kpL/223//wD//23//5IA/7YA29sAbdsAAP8ASf/bAP//SUlJAAAAAAAA////ttv/27b//7b//5L//7a2/9uS//9J//9ttv9Jkv9tSf/bktv/kpKSAAAAAAAA',
'nestopia-yuv':'ZmZmACqIFBKnOwCkXAB+bgBAbAcAVh0AMzUADEgAAFIAAE8IAEBNAAAAAAAAAAAAra2tFV/ZQkD/dSf+oBrMtx57tTEgmU4Aa20AOIcADZMAAI8yAHyNAAAAAAAAAAAA////ZLD/kpD/xnb/8mr//27M/4Fw6p4ivL4AiNgAXOQwReCCSM3eT09PAAAAAAAA////wN//09L/6Mj/+sL//8Tq/8zF99il5OWUz++WvfSrs/PMtevyuLi4AAAAAAAA','sony-cxa2025as':'WFhYACOMABObLQWFXQBSegAXeggAXxgANSoACTkAAD8AADwiADJdAAAAAAAAAAAAoaGhAFPuFTz+YCjkqR2Y1B5B0iwAqkQAbF4ALXMAAH0GAHhSAGmpAAAAAAAAAAAA////H6X+Xon+tXL+/mX2/meQ/nc8/pMIxLIAecoQOtVKEdGkBr/+QkJCAAAAAAAA////oNn+vcz+4cL+/rz7/r3Q/sWp/tGO6d6Gx+mSqO6wlezZkeT+rKysAAAAAAAA',
'unsaturated-v6':'a2trAB6HHwuWOwyHWQ1hXgUoVREARhsAMDIACkgAAE4AAEYZADpYAAAAAAAAAAAAsrKyGlPRSDXucSPsmh63pR5ipS0Zh0sAZ2kAKYQAA4sAAIJAAHiRAAAAAAAAAAAA////Y639kIr+uXf853H+92/J9YNq3ZwpvbgHhNEHW9w7SNd9SMzOVVVVAAAAAAAA////xOP+19X+5s3++cr+/snw/tHH99ys6Oic0fKdv/Sxt/XNt/Duvr6+AAAAAAAA'};
function yb(a){a=void 0===a?'fceux':a;var b=xb[a];if(b){A('Creating "'+a+'" palette');if('undefined'!==typeof window&&'function'===typeof window.atob)a=window.atob(b);else if('function'===typeof Buffer)a=Buffer.from(b,'base64').toString('binary');else throw Error('Unable to decode base64 string');if(192!==a.length)throw Error('Palette data does not contain 64 entries');b=new Uint32Array(64);for(var d=0;64>d;d++){var f=3*d;b[d]=sb(a.charCodeAt(f),a.charCodeAt(f+1),a.charCodeAt(f+2))}return b}throw Error('Invalid palette: '+
n(a));};for(var H=new Uint32Array(262),J=0;J<H.length;J++){239>=J&&(H[J]|=2,H[J]|=512,H[J]|=2048,H[J]|=1024);if(239>=J||261===J)H[J]|=4,H[J]|=8,H[J]|=16,H[J]|=32,H[J]|=64,H[J]|=128,H[J]|=256,H[J]|=8192,H[J]|=16384,H[J]|=32768;if(7>=J||232<=J&&239>=J)H[J]|=4096}H[241]|=131072;H[241]|=262144;H[261]|=65536;H[261]|=524288;H[261]|=1048576;
for(var K=new Uint32Array(341),L=0;L<K.length;L++){1<=L&&256>=L&&(K[L]|=2,K[L]|=4096);if(1===(L&7)||339===L)K[L]|=4;3===(L&7)&&339!==L&&(K[L]|=8);5===(L&7)&&(K[L]|=256>=L||321<=L?16:64);7===(L&7)&&(K[L]|=256>=L||321<=L?32:128);if(0===(L&7)&&8<=L&&256>=L||328===L||336===L)K[L]|=8192;if(1===(L&7)&&9<=L&&257>=L||329===L||337===L)K[L]|=256;if(1<=L&&256>=L||321<=L&&336>=L)K[L]|=512;280<=L&&304>=L&&(K[L]|=65536);1<=L&&8>=L&&(K[L]|=2048);1<=L&&3>=L&&(K[L]|=262144)}K[1]|=131072;K[1]|=524288;K[65]|=1024;
K[256]|=16384;K[257]|=32768;K[338]|=1048576;function zb(){this.x=0;this.Nc=this.ad=!1;this.Uc=0;this.Pc=!1;this.Wc=this.Vc=this.Qa=0};function Ab(){A('Initializing PPU');this.h=261;this.f=this.i=0;this.wb=!1;this.U=0;this.vb=this.Gb=this.Fb=this.Rc=!1;this.R=0;this.j=null;this.Kb=!1;this.O=0;this.Lc=null;this.zb=Array(8);this.ua=null;this.la=this.m=0;this.va=Array(261);this.Db=new Uint8Array(261);this.l=new Uint8Array(256);this.$=Array(8);this.Hb=this.c=this.g=this.Pa=0;this.s=!1;this.na=this.Eb=this.Bb=this.Wb=this.ma=this.v=this.Sc=this.Jc=this.ub=this.dc=this.Oc=this.Ab=this.Qc=this.Qa=this.lc=this.hc=this.oc=this.nc=this.gc=
this.ec=this.yb=this.xb=this.S=this.P=this.L=0;this.C=this.K=null}c=Ab.prototype;c.connect=function(a){A('Connecting PPU');this.K=a.K;this.C=a.C};
c.reset=function(){A('Resetting PPU');this.l.fill(0);for(var a=0;a<this.$.length;a++)this.$[a]=new zb;Da(this,0);Ea(this,0);this.Hb=this.c=this.g=this.Pa=this.na=this.Eb=this.Bb=0;this.s=!1;this.lc=this.hc=this.oc=this.nc=this.gc=this.ec=this.yb=this.xb=this.S=this.P=this.L=0;this.h=261;this.f=this.i=0;this.vb=this.Gb=!1;this.R=0;this.wb=!1;this.la=this.m=0;this.va.fill(null);this.Db.fill(0)};c.Sa=function(a){A('Setting PPU region parameters');this.Rc=a.Xc};
function Da(a,b){a.Qc=b>>>2&1;a.Ab=b<<9&4096;a.Oc=b<<8&4096;a.dc=b>>>5&1;a.ub=b>>>7}function Ea(a,b){a.Jc=~b>>>1&1;a.Sc=~b>>>2&1;a.v=b>>>3&1;a.ma=b>>>4&1;a.Wb=b>>>5&7}c.uc=function(){var a=this.Bb<<5|this.Eb<<6|this.na<<7;this.na=0;this.s=!1;this.f&131072&&(this.Gb=!0);this.f&262144&&(this.vb=!0);return a};c.Bc=function(a){(this.s=!this.s)?this.g=this.g&255|(a&63)<<8:this.c=this.g=this.g&65280|a};function Fa(a){a.c=a.c+(a.Qc?32:1)&65535}
c.w=function(){if(this.ma||this.v){if(this.f&4)this.U=8192|this.c&4095,this.Qa=this.Oc+(Ta(this.C,this.U)<<4)+(this.c>>>12&7);else if(this.f&8){this.U=(9152|this.c&3072)+(this.c>>>4&56|this.c>>>2&7);var a=Ta(this.C,this.U)>>>(this.c>>>4&4|this.c&2)&3;this.hc=a&1;this.lc=a>>>1&1}else this.f&16?(this.U=this.Qa,this.nc=Sa(this.C,this.U)):this.f&32?(this.U=this.Qa+8,this.oc=Sa(this.C,this.U)):this.f&64?this.la<this.m?(a=this.$[this.la],this.U=a.Qa,a.Vc=Sa(this.C,this.U)):this.U=this.Ab|4080:this.f&128&&
(this.la<this.m?(a=this.$[this.la++],this.U=a.Qa+8,a.Wc=Sa(this.C,this.U)):this.U=this.Ab|4080);if(this.f&1024){this.m=this.la=0;a=this.dc?16:8;for(var b=this.h+1,d=b-a+1,f=0;f<this.l.length;f+=4){var h=this.l[f]+1;if(!(h<d||h>b)){if(8<=this.m){this.Bb=1;break}var l=this.Ab,m=this.l[f+1];this.dc&&(l=(m&1)<<12,m&=254);var p=this.l[f+2];h=b-h;p&128&&(h=a-h-1);8<=h&&(h-=8,m++);var r=this.$[this.m];r.x=this.l[f+3];r.ad=0===f;r.Nc=p&64;r.Uc=16|(p&3)<<2;r.Pc=0===(p&32);r.Qa=l+(m<<4)+h;this.m++}}}this.f&
256&&(this.P|=this.nc,this.S|=this.oc,this.ec=this.hc,this.gc=this.lc);this.f&2&&(a=!this.v||this.Jc&&this.f&2048?0:this.yb<<this.L>>4&8|this.xb<<this.L>>5&4|this.S<<this.L>>14&2|this.P<<this.L>>15&1,b=!this.ma||this.Sc&&this.f&2048?0:this.Db[this.i],a&3?b&3&&(d=this.va[this.i],d.ad&&256!==this.i&&(this.Eb=1),d.Pc&&(a=b)):a=b&3?b:0,this.Rc&&this.f&4096?this.j[this.O++]=wb:(a=this.C.Ya[Ua(a)],this.j[this.O++]=this.ua[a&63]));this.f&512&&(this.P<<=1,this.S<<=1,this.xb=this.xb<<1|this.ec,this.yb=this.yb<<
1|this.gc);this.f&8192&&(31===(this.c&31)?(this.c&=65504,this.c^=1024):this.c+=1);this.f&16384&&(28672===(this.c&28672)?(this.c&=4095,992===(this.c&992)?this.c&=64543:928===(this.c&992)?(this.c&=64543,this.c^=2048):this.c+=32):this.c+=4096);this.f&32768&&(this.c=this.c&31712|this.g&1055);this.f&65536&&(this.c=this.c&1055|this.g&31712)}else this.f&2&&(this.j[this.O++]=wb),this.U=this.c;this.R&&(this.ub?--this.R||this.vb||(a=this.K,a.g|=2):this.R=0);this.f&131072?(this.Gb||(this.na=1),this.Kb=this.Fb=
!0,this.R=2):this.f&524288&&(this.Fb=!1,this.na=0,this.vb=this.Gb=!1,this.Bb=this.Eb=0);this.f&1048576&&this.wb&&(this.ma||this.v)&&this.i++;this.i++;if(340<this.i&&(this.i=0,this.h++,261<this.h&&(this.h=0,this.wb=!this.wb,this.O=0),239>=this.h&&(this.va.fill(null),this.Db.fill(0),0<this.h)))for(a=0;a<this.m;a++)for(b=this.$[a],d=0;8>d;d++){f=b.x+d+1;if(256<f)break;!this.va[f]&&(l=b.Nc?d:d^7,l=(b.Wc>>>l&1)<<1|b.Vc>>>l&1)&&(this.va[f]=b,this.Db[f]=b.Uc|l)}this.f=H[this.h]&K[this.i]};
c.vc=function(){for(var a=0;16>a;a++)for(var b=a<<3,d=0;32>d;d++)for(var f=d<<3,h=((d&16)<<4|a<<4|d&15)<<4,l=0;8>l;l++)for(var m=b+l,p=Sa(this.C,h+l),r=Sa(this.C,h+l+8),q=0;8>q;q++){var G=q^7;this.j[256*m+(f+q)]=this.ua[this.C.Ya[Ua((r>>G&1)<<1|p>>G&1)]&63]}for(a=0;4>a;a++)for(b=28*a+128,d=0;8>d;d++)for(f=d<<5,h=this.C.Ya[Ua(a<<3|d)],l=b;l<b+28;l++)for(m=f;m<f+32;m++)this.j[256*l+m]=this.ua[h&63]};var P=Array(255);function Bb(){A('Initializing CPU');this.P=!1;this.L=this.s=this.R=this.m=this.O=this.j=this.l=this.h=this.c=this.i=this.f=this.$=this.v=this.g=this.S=0;this.o=this.u=this.ca=this.A=this.N=null}c=Bb.prototype;c.connect=function(a){A('Connecting CPU');this.A=a.A;this.u=a.u;this.o=a.o;this.ca=a.ca};c.Aa=function(a){this.N=a};
c.reset=function(){A('Resetting CPU');this.g=0;this.P=!1;this.l=this.h=this.c=this.i=0;Cb(this,0);for(var a=0;8>a;a++)this.A.write(a,255);this.A.write(8,247);this.A.write(9,239);this.A.write(10,223);this.A.write(15,191);for(a=16;2048>a;a++)this.A.write(a,255);for(a=16384;16400>a;a++)this.A.write(a,0);Db(this)};
c.step=function(){var a=this.ca.Mb()||this.o.Mb();if(this.g&&!a)a:{if(this.g&1)Db(this);else if(this.g&2)Eb(this,this.f),Fb(this,Gb(this)),this.m=1,this.f=Hb(this,65530),kb(this,2);else{if(this.v)break a;Eb(this,this.f);Fb(this,Gb(this));this.m=1;this.f=Hb(this,65534)}this.w();this.w()}if(this.P||a)this.w();else if(a=P[Ib(this)]){this.v=this.m;this.S=a[2];var b=e(a);a=b.next().value;b=b.next().value.call(this);a.call(this,b)}else Aa('CPU halted!'),this.P=!0};
function Db(a){Q(a,16405,0);Q(a,16407,a.o.Ic);a.i=a.i-3&255;a.m=1;a.f=Hb(a,65532);kb(a,1);a.w();a.P=!1}function Ib(a){return S(a,Jb(a,1))}function Jb(a,b){var d=a.f;a.f=a.f+b&65535;return d}function S(a,b){a.w();return a.A.read(b)}function Hb(a,b){var d=b+1&65535;b=S(a,b);return S(a,d)<<8|b}function Kb(a,b){var d=b&65280|b+1&255;b=S(a,b);return S(a,d)<<8|b}function Q(a,b,d){a.w();a.A.write(b,d);return d}function Lb(a,b){var d=S(a,b);return Q(a,b,d)}function Fb(a,b){Q(a,256+a.i,b);a.i=a.i-1&255}
function Eb(a,b){Fb(a,b>>>8);Fb(a,b&255)}function Mb(a){a.i=a.i+1&255;return S(a,256+a.i)}function Gb(a){return a.j|a.O<<1|a.m<<2|a.R<<3|32|a.s<<6|a.L<<7}function Cb(a,b){a.j=b&1;a.O=b>>>1&1;a.m=b>>>2&1;a.R=b>>>3&1;a.s=b>>>6&1;a.L=b>>>7}function kb(a,b){a.g&=~b}c.w=function(){2<this.o.Y.h||(this.ca.w(),this.N.w());this.u.w();this.u.w();this.u.w();this.o.w()};c.F=function(){this.w()};c.Ib=function(){this.w()};c.M=function(){return Jb(this,1)};c.D=function(){return Ib(this)};
c.G=function(){var a=Ib(this),b=this.h;S(this,a);return a+b&255};c.Vb=function(){var a=Ib(this),b=this.l;S(this,a);return a+b&255};c.B=function(){return Hb(this,Jb(this,2))};c.J=function(){return Nb(this,Hb(this,Jb(this,2)),this.h)};c.T=function(){return Nb(this,Hb(this,Jb(this,2)),this.l)};c.za=function(){var a=Ib(this);return this.f+(a&128?a-256:a)&65535};c.he=function(){return Kb(this,Hb(this,Jb(this,2)))};c.W=function(){return Kb(this,this.G())};
c.X=function(){var a=Kb(this,Ib(this));return Nb(this,a,this.l)};function Nb(a,b,d){d=b+d&65535;a.$=(b&65280)!==(d&65280);(a.S&2||a.$)&&S(a,b&65280|d&255);return d}c.I=function(){this.S&1&&this.w()};c.qd=function(){this.j=0};c.sd=function(){this.v=this.m;this.m=0};c.rd=function(){this.R=0};c.td=function(){this.s=0};c.Hd=function(){this.j=1};c.Jd=function(){this.v=this.m;this.m=1};c.Id=function(){this.R=1};c.Ka=function(a){Q(this,a,this.c)};c.ac=function(a){Q(this,a,this.h)};
c.Cb=function(a){Q(this,a,this.c&this.h)};c.bc=function(a){Q(this,a,this.l)};c.$b=function(a){Ob(this,a,this.c&this.h)};c.Kd=function(a){Ob(this,a,this.h)};c.Ld=function(a){Ob(this,a,this.l)};c.wa=function(a){T(this,S(this,a))};c.bb=function(a){Pb(this,S(this,a))};c.cb=function(a){a=S(this,a);Qb(this,a);this.l=a};c.Da=function(a){a=S(this,a);T(this,a);Pb(this,a)};c.Ad=function(a){this.i&=S(this,a);T(this,this.i);Pb(this,this.i)};c.Pd=function(){Pb(this,this.c)};
c.Qd=function(){var a=this.c;Qb(this,a);this.l=a};c.Sd=function(){T(this,this.h)};c.Ud=function(){T(this,this.l)};c.Rd=function(){Pb(this,this.i)};c.Td=function(){this.i=this.h};c.Bd=function(){Fb(this,this.c)};c.Cd=function(){Fb(this,Gb(this)|16)};c.Dd=function(){this.w();T(this,Mb(this))};c.Ed=function(){this.w();this.v=this.m;Cb(this,Mb(this))};c.ba=function(a){return T(this,this.c&S(this,a))};c.xa=function(a){T(this,this.c|S(this,a))};c.ta=function(a){T(this,this.c^S(this,a))};
c.Ec=function(a){a=S(this,a);this.O=!(this.c&a)|0;this.s=a>>>6&1;this.L=a>>>7};c.ab=function(a){return Rb(this,a,Lb(this,a)+1&255)};c.wd=function(){Pb(this,this.h+1&255)};c.xd=function(){var a=this.l+1&255;Qb(this,a);this.l=a};c.$a=function(a){return Rb(this,a,Lb(this,a)-1&255)};c.ud=function(){Pb(this,this.h-1&255)};c.vd=function(){var a=this.l-1&255;Qb(this,a);this.l=a};c.sa=function(a){Sb(this,this.c,S(this,a))};c.Xb=function(a){Sb(this,this.h,S(this,a))};
c.Yb=function(a){Sb(this,this.l,S(this,a))};c.gd=function(a){Tb(this,!this.j,a)};c.hd=function(a){Tb(this,this.j,a)};c.ld=function(a){Tb(this,!this.O,a)};c.jd=function(a){Tb(this,this.O,a)};c.od=function(a){Tb(this,!this.s,a)};c.pd=function(a){Tb(this,this.s,a)};c.md=function(a){Tb(this,!this.L,a)};c.kd=function(a){Tb(this,this.L,a)};c.Fc=function(a){this.f=a};c.zd=function(a){this.w();Eb(this,this.f-1&65535);this.f=a};c.Gd=function(){this.w();this.w();this.f=(Mb(this)|Mb(this)<<8)+1&65535};
c.nd=function(){Jb(this,1);Eb(this,this.f);Fb(this,Gb(this)|16);this.m=this.v=1;this.f=Hb(this,this.g&2?65530:65534)};c.Fd=function(){this.w();Cb(this,Mb(this));this.v=this.m;this.f=Mb(this)|Mb(this)<<8};c.ra=function(a){Ub(this,S(this,a))};c.oa=function(a){Ub(this,S(this,a)^255)};c.Ta=function(a){return Vb(this,a,this.wc,!1)};c.Ea=function(a){return Vb(this,a,this.Yc,!1)};c.Ua=function(a){return Vb(this,a,this.wc,!0)};c.Ga=function(a){return Vb(this,a,this.Yc,!0)};
c.Ba=function(a){Sb(this,this.c,this.$a(a))};c.Ca=function(a){Ub(this,this.ab(a)^255)};c.Ia=function(a){T(this,this.c|this.Ta(a))};c.Ja=function(a){T(this,this.c^this.Ea(a))};c.Fa=function(a){T(this,this.c&this.Ua(a))};c.Xd=function(a){T(this,this.h&this.ba(a))};c.Ha=function(a){Ub(this,this.Ga(a))};c.dd=function(a){this.h=Sb(this,this.c&this.h,S(this,a))};c.Cc=function(a){this.wc(this.ba(a),!1)};c.bd=function(a){this.ba(a);this.Ea(null)};
c.cd=function(a){this.ba(a);this.Ga(null);this.j=this.c>>>6&1;this.s=this.c>>>5&1^this.j};c.Od=function(a){this.i=this.c&this.h;this.$b(a)};function T(a,b){Qb(a,b);return a.c=b}function Pb(a,b){Qb(a,b);a.h=b}function Rb(a,b,d){Qb(a,d);return Q(a,b,d)}function Ob(a,b,d){a.$?Q(a,b,a.A.read(b)):Q(a,b,d&(b>>>8)+1)}function Ub(a,b){var d=a.c+b+a.j;a.j=d>>>8&1;a.s=((a.c^d)&(b^d))>>>7&1;T(a,d&255)}function Sb(a,b,d){b-=d;a.j=0<=b|0;Qb(a,b);return b&255}
function Tb(a,b,d){b&&(a.w(),(a.f&65280)!==(d&65280)&&a.w(),a.f=d)}function Vb(a,b,d,f){if(null!=b)return d=d.call(a,Lb(a,b),f),Rb(a,b,d);b=d.call(a,a.c,f);return T(a,b)}c.wc=function(a,b){b&=this.j;this.j=a>>>7;return(a<<1|b)&255};c.Yc=function(a,b){b=(b&this.j)<<7;this.j=a&1;return a>>>1|b};function Qb(a,b){a.O=!(b&255)|0;a.L=b>>>7&1}var U=Bb.prototype;P[26]=[U.I,U.F,0];P[58]=[U.I,U.F,0];P[90]=[U.I,U.F,0];P[122]=[U.I,U.F,0];P[218]=[U.I,U.F,0];P[234]=[U.I,U.F,0];P[250]=[U.I,U.F,0];
P[128]=[U.I,U.M,1];P[130]=[U.I,U.M,1];P[137]=[U.I,U.M,1];P[194]=[U.I,U.M,1];P[226]=[U.I,U.M,1];P[4]=[U.I,U.D,1];P[68]=[U.I,U.D,1];P[100]=[U.I,U.D,1];P[20]=[U.I,U.G,1];P[52]=[U.I,U.G,1];P[84]=[U.I,U.G,1];P[116]=[U.I,U.G,1];P[212]=[U.I,U.G,1];P[244]=[U.I,U.G,1];P[12]=[U.I,U.B,1];P[28]=[U.I,U.J,1];P[60]=[U.I,U.J,1];P[92]=[U.I,U.J,1];P[124]=[U.I,U.J,1];P[220]=[U.I,U.J,1];P[252]=[U.I,U.J,1];P[24]=[U.qd,U.F,0];P[88]=[U.sd,U.F,0];P[216]=[U.rd,U.F,0];P[184]=[U.td,U.F,0];P[56]=[U.Hd,U.F,0];
P[120]=[U.Jd,U.F,0];P[248]=[U.Id,U.F,0];P[133]=[U.Ka,U.D,0];P[149]=[U.Ka,U.G,0];P[141]=[U.Ka,U.B,0];P[157]=[U.Ka,U.J,2];P[153]=[U.Ka,U.T,2];P[129]=[U.Ka,U.W,0];P[145]=[U.Ka,U.X,2];P[134]=[U.ac,U.D,0];P[150]=[U.ac,U.Vb,0];P[142]=[U.ac,U.B,0];P[135]=[U.Cb,U.D,0];P[151]=[U.Cb,U.Vb,0];P[143]=[U.Cb,U.B,0];P[131]=[U.Cb,U.W,0];P[132]=[U.bc,U.D,0];P[148]=[U.bc,U.G,0];P[140]=[U.bc,U.B,0];P[147]=[U.$b,U.X,2];P[159]=[U.$b,U.T,2];P[158]=[U.Kd,U.T,2];P[156]=[U.Ld,U.J,2];P[169]=[U.wa,U.M,0];P[165]=[U.wa,U.D,0];
P[181]=[U.wa,U.G,0];P[173]=[U.wa,U.B,0];P[189]=[U.wa,U.J,0];P[185]=[U.wa,U.T,0];P[161]=[U.wa,U.W,0];P[177]=[U.wa,U.X,0];P[162]=[U.bb,U.M,0];P[166]=[U.bb,U.D,0];P[182]=[U.bb,U.Vb,0];P[174]=[U.bb,U.B,0];P[190]=[U.bb,U.T,0];P[160]=[U.cb,U.M,0];P[164]=[U.cb,U.D,0];P[180]=[U.cb,U.G,0];P[172]=[U.cb,U.B,0];P[188]=[U.cb,U.J,0];P[171]=[U.Da,U.M,0];P[167]=[U.Da,U.D,0];P[183]=[U.Da,U.Vb,0];P[175]=[U.Da,U.B,0];P[191]=[U.Da,U.T,0];P[163]=[U.Da,U.W,0];P[179]=[U.Da,U.X,0];P[187]=[U.Ad,U.T,0];P[170]=[U.Pd,U.F,0];
P[168]=[U.Qd,U.F,0];P[138]=[U.Sd,U.F,0];P[152]=[U.Ud,U.F,0];P[154]=[U.Td,U.F,0];P[186]=[U.Rd,U.F,0];P[72]=[U.Bd,U.F,0];P[8]=[U.Cd,U.F,0];P[104]=[U.Dd,U.F,0];P[40]=[U.Ed,U.F,0];P[41]=[U.ba,U.M,0];P[37]=[U.ba,U.D,0];P[53]=[U.ba,U.G,0];P[45]=[U.ba,U.B,0];P[61]=[U.ba,U.J,0];P[57]=[U.ba,U.T,0];P[33]=[U.ba,U.W,0];P[49]=[U.ba,U.X,0];P[9]=[U.xa,U.M,0];P[5]=[U.xa,U.D,0];P[21]=[U.xa,U.G,0];P[13]=[U.xa,U.B,0];P[29]=[U.xa,U.J,0];P[25]=[U.xa,U.T,0];P[1]=[U.xa,U.W,0];P[17]=[U.xa,U.X,0];P[73]=[U.ta,U.M,0];
P[69]=[U.ta,U.D,0];P[85]=[U.ta,U.G,0];P[77]=[U.ta,U.B,0];P[93]=[U.ta,U.J,0];P[89]=[U.ta,U.T,0];P[65]=[U.ta,U.W,0];P[81]=[U.ta,U.X,0];P[36]=[U.Ec,U.D,0];P[44]=[U.Ec,U.B,0];P[230]=[U.ab,U.D,0];P[246]=[U.ab,U.G,0];P[238]=[U.ab,U.B,0];P[254]=[U.ab,U.J,2];P[232]=[U.wd,U.F,0];P[200]=[U.xd,U.F,0];P[198]=[U.$a,U.D,0];P[214]=[U.$a,U.G,0];P[206]=[U.$a,U.B,0];P[222]=[U.$a,U.J,2];P[202]=[U.ud,U.F,0];P[136]=[U.vd,U.F,0];P[201]=[U.sa,U.M,0];P[197]=[U.sa,U.D,0];P[213]=[U.sa,U.G,0];P[205]=[U.sa,U.B,0];
P[221]=[U.sa,U.J,0];P[217]=[U.sa,U.T,0];P[193]=[U.sa,U.W,0];P[209]=[U.sa,U.X,0];P[224]=[U.Xb,U.M,0];P[228]=[U.Xb,U.D,0];P[236]=[U.Xb,U.B,0];P[192]=[U.Yb,U.M,0];P[196]=[U.Yb,U.D,0];P[204]=[U.Yb,U.B,0];P[144]=[U.gd,U.za,0];P[176]=[U.hd,U.za,0];P[208]=[U.ld,U.za,0];P[240]=[U.jd,U.za,0];P[80]=[U.od,U.za,0];P[112]=[U.pd,U.za,0];P[16]=[U.md,U.za,0];P[48]=[U.kd,U.za,0];P[76]=[U.Fc,U.B,0];P[108]=[U.Fc,U.he,0];P[32]=[U.zd,U.B,0];P[96]=[U.Gd,U.F,0];P[0]=[U.nd,U.F,0];P[64]=[U.Fd,U.F,0];P[105]=[U.ra,U.M,0];
P[101]=[U.ra,U.D,0];P[117]=[U.ra,U.G,0];P[109]=[U.ra,U.B,0];P[125]=[U.ra,U.J,0];P[121]=[U.ra,U.T,0];P[97]=[U.ra,U.W,0];P[113]=[U.ra,U.X,0];P[233]=[U.oa,U.M,0];P[235]=[U.oa,U.M,0];P[229]=[U.oa,U.D,0];P[245]=[U.oa,U.G,0];P[237]=[U.oa,U.B,0];P[253]=[U.oa,U.J,0];P[249]=[U.oa,U.T,0];P[225]=[U.oa,U.W,0];P[241]=[U.oa,U.X,0];P[10]=[U.Ta,U.Ib,0];P[6]=[U.Ta,U.D,0];P[22]=[U.Ta,U.G,0];P[14]=[U.Ta,U.B,0];P[30]=[U.Ta,U.J,2];P[74]=[U.Ea,U.Ib,0];P[70]=[U.Ea,U.D,0];P[86]=[U.Ea,U.G,0];P[78]=[U.Ea,U.B,0];
P[94]=[U.Ea,U.J,2];P[42]=[U.Ua,U.Ib,0];P[38]=[U.Ua,U.D,0];P[54]=[U.Ua,U.G,0];P[46]=[U.Ua,U.B,0];P[62]=[U.Ua,U.J,2];P[106]=[U.Ga,U.Ib,0];P[102]=[U.Ga,U.D,0];P[118]=[U.Ga,U.G,0];P[110]=[U.Ga,U.B,0];P[126]=[U.Ga,U.J,2];P[199]=[U.Ba,U.D,0];P[215]=[U.Ba,U.G,0];P[207]=[U.Ba,U.B,0];P[223]=[U.Ba,U.J,2];P[219]=[U.Ba,U.T,2];P[195]=[U.Ba,U.W,0];P[211]=[U.Ba,U.X,2];P[231]=[U.Ca,U.D,0];P[247]=[U.Ca,U.G,0];P[239]=[U.Ca,U.B,0];P[255]=[U.Ca,U.J,2];P[251]=[U.Ca,U.T,2];P[227]=[U.Ca,U.W,0];P[243]=[U.Ca,U.X,2];
P[7]=[U.Ia,U.D,0];P[23]=[U.Ia,U.G,0];P[15]=[U.Ia,U.B,0];P[31]=[U.Ia,U.J,2];P[27]=[U.Ia,U.T,2];P[3]=[U.Ia,U.W,0];P[19]=[U.Ia,U.X,2];P[71]=[U.Ja,U.D,0];P[87]=[U.Ja,U.G,0];P[79]=[U.Ja,U.B,0];P[95]=[U.Ja,U.J,2];P[91]=[U.Ja,U.T,2];P[67]=[U.Ja,U.W,0];P[83]=[U.Ja,U.X,2];P[39]=[U.Fa,U.D,0];P[55]=[U.Fa,U.G,0];P[47]=[U.Fa,U.B,0];P[63]=[U.Fa,U.J,2];P[59]=[U.Fa,U.T,2];P[35]=[U.Fa,U.W,0];P[51]=[U.Fa,U.X,2];P[139]=[U.Xd,U.M,0];P[103]=[U.Ha,U.D,0];P[119]=[U.Ha,U.G,0];P[111]=[U.Ha,U.B,0];P[127]=[U.Ha,U.J,2];
P[123]=[U.Ha,U.T,2];P[99]=[U.Ha,U.W,0];P[115]=[U.Ha,U.X,2];P[203]=[U.dd,U.M,0];P[11]=[U.Cc,U.M,0];P[43]=[U.Cc,U.M,0];P[75]=[U.bd,U.M,0];P[107]=[U.cd,U.M,0];P[155]=[U.Od,U.T,2];var Wb=[10,254,20,2,40,4,80,6,160,8,60,10,14,12,26,14,12,16,24,18,48,20,96,22,192,24,72,26,16,28,32,30];var Xb=[[0,1,0,0,0,0,0,0],[0,1,1,0,0,0,0,0],[0,1,1,1,1,0,0,0],[1,0,0,1,1,1,1,1]];function Yb(a){A('Initializing pulse channel #'+a);this.la=a;this.l=!1;this.gain=1;this.f=this.c=this.O=0;this.ma=this.m=!1;this.s=0;this.L=!1;this.g=this.h=0;this.$=!1;this.v=0;this.ua=!1;this.i=0;this.va=this.P=!1;this.na=this.j=this.S=this.R=0}c=Yb.prototype;c.reset=function(){A('Resetting pulse channel #'+this.la);this.f=this.i=this.g=this.h=this.c=this.O=0;this.l=!1;Ha(this,0);Ia(this,0);this.qa(0);this.pa(0)};
function Ha(a,b){a.na=(b&192)>>>6;a.m=0!==(b&32);a.ma=0!==(b&16);a.s=b&15;a.$=a.m;a.v=a.s}function Ia(a,b){a.ua=0!==(b&128);a.R=(b&112)>>>4;a.va=0!==(b&8);a.S=b&7;a.P=!0}c.qa=function(a){this.c=this.c&1792|a&255};c.pa=function(a){this.l&&(this.f=Wb[(a&248)>>>3]);this.c=this.c&255|(a&7)<<8;this.j=0;this.L=!0};c.w=function(){0>=--this.O&&(this.O=this.c+1<<1,this.j=this.j+1&7)};function Zb(a){a.L?(a.L=!1,a.h=a.v,a.g=15):0<a.h?a.h--:(a.h=a.v,0<a.g?a.g--:a.$&&(a.g=15))}
function $b(a){0<a.i?a.i--:(a.ua&&a.S&&8<=a.c&&2048>a.c+ac(a)&&(a.c+=ac(a)),a.i=a.R);a.P&&(a.P=!1,a.i=a.R)}function ac(a){var b=a.c>>>a.S;return a.va?1===a.la?~b:-b:b}c.Z=function(){return this.f&&8<=this.c&&2048>this.c+ac(this)?this.gain*(this.ma?this.s:this.g)*Xb[this.na][this.j]:0};var bc=[15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15];function cc(){A('Initializing triangle channel');this.i=!1;this.gain=1;this.c=this.f=this.l=0;this.j=!1;this.v=this.g=0;this.m=this.s=!1;this.h=15}c=cc.prototype;c.reset=function(){A('Resetting triangle channel');this.c=this.g=this.h=this.f=this.l=0;this.i=!1;Ja(this,0);this.qa(0);this.pa(0)};function Ja(a,b){a.j=0!==(b&128);a.v=b&127;a.s=a.j}c.qa=function(a){this.f=this.f&1792|a&255};
c.pa=function(a){this.i&&(this.c=Wb[(a&248)>>>3]);this.f=this.f&255|(a&7)<<8;this.m=!0};c.w=function(){0>=--this.l&&(this.l=this.f+1,this.c&&this.g&&3<this.f&&(this.h=this.h+1&31))};c.Z=function(){return this.gain*bc[this.h]};function dc(){A('Initializing noise channel');this.j=!1;this.gain=1;this.S=!1;this.O=this.v=0;this.R=null;this.c=0;this.P=this.s=!1;this.i=0;this.m=!1;this.f=this.h=0;this.L=!1;this.g=this.l=0}c=dc.prototype;c.reset=function(){A('Resetting noise channel');this.f=this.h=this.v=0;this.g=1;this.c=0;this.j=!1;Ka(this,0);this.qa(0);this.pa(0)};c.Sa=function(a){this.R=a.Tc};function Ka(a,b){a.s=0!==(b&32);a.P=0!==(b&16);a.i=b&15;a.L=a.s;a.l=a.i}c.qa=function(a){this.S=0!==(a&128);this.O=this.R[a&15]};
c.pa=function(a){this.j&&(this.c=Wb[(a&248)>>>3]);this.m=!0};c.w=function(){0>=--this.v&&(this.v=this.O,this.g=this.g>>>1|(this.g&1^this.g>>>(this.S?6:1)&1)<<14)};c.Z=function(){return!this.c||this.g&1?0:this.gain*(this.P?this.i:this.f)};function ec(){A('Initializing DMC channel');this.c=0;this.gain=1;this.R=this.L=0;this.P=null;this.f=this.i=this.s=this.m=0;this.S=!1;this.g=this.j=-1;this.h=this.O=0;this.l=this.v=!1;this.A=this.K=null}c=ec.prototype;c.connect=function(a){A('Connecting DMC channel');this.K=a.K;this.A=a.A};c.reset=function(){A('Resetting DMC channel');this.L=0;this.g=this.j=-1;this.h=this.O=0;Ma(this,!1);La(this,0);this.c=0;this.m=49152;this.s=1};
function Ma(a,b){b?0===a.f&&(a.i=a.m,a.f=a.s):a.f=0;a.l=!1;kb(a.K,8)}c.Sa=function(a){this.P=a.Hc};function La(a,b){a.v=0!==(b&128);a.S=0!==(b&64);a.R=a.P[b&15];a.v||(a.l=!1,kb(a.K,8))}
c.w=function(){0<this.h&&this.h--;if(0>=--this.L){this.L=this.R;if(0>this.j&&0<this.f&&(this.j=this.A.read(this.i),this.h=4,65535>this.i?this.i++:this.i=32768,0>=--this.f))if(this.S)this.i=this.m,this.f=this.s;else if(this.v){this.l=!0;var a=this.K;a.g|=8}0>=--this.O&&(this.O=8,this.g=this.j,this.j=-1);0<=this.g&&(this.g&1?125>=this.c&&(this.c+=2):2<=this.c&&(this.c-=2),this.g>>>=1)}};c.Z=function(){return this.gain*this.c};function fc(){A('Initializing APU');this.ea=new Yb(1);this.fa=new Yb(2);this.ha=new cc;this.da=new dc;this.Y=new ec;this.s=[this.ea,this.fa,this.ha,this.da,this.Y];this.c=-1;this.lb=this.kb=null;this.Ic=this.i=0;this.g=!1;this.f=0;this.l=this.j=!1;this.v=this.m=this.sampleRate=0;this.K=this.h=null}c=fc.prototype;c.connect=function(a){A('Connecting APU');this.K=a.K;this.Y.connect(a)};
c.reset=function(){A('Resetting APU');this.ea.reset();this.fa.reset();this.ha.reset();this.da.reset();this.Y.reset();gc(this);Na(this,0)};c.Sa=function(a){A('Setting APU region parameters');this.kb=a.kb;this.lb=a.lb;this.v=29829.55*a.pc;this.da.Sa(a);this.Y.Sa(a)};c.qb=function(a){this.sampleRate=a};function hc(a,b){A((b?'Setting':'Removing')+' APU callback');a.h=b}c.sb=function(a,b){A('Setting volume of APU channel #'+a+' to '+b);this.s[a].gain=b};c.Xa=function(a){return this.s[a].gain};
function Na(a,b){a.Ic=b;a.g=0!==(b&128);a.l=0!==(b&64);a.i=4;a.f=0;0>a.c&&(a.c=ic(a));a.l&&gc(a);a.g&&(jc(a),kc(a))}function ic(a){return(a.g?a.lb:a.kb)[a.f]}function gc(a){a.j=!1;kb(a.K,4)}c.uc=function(){var a=0<this.ea.f|(0<this.fa.f)<<1|(0<this.ha.c)<<2|(0<this.da.c)<<3|(0<this.Y.f)<<4|this.j<<6|this.Y.l<<7;gc(this);return a};c.Mb=function(){return 0<this.Y.h};
c.w=function(){this.i&&0>=--this.i&&(this.c=ic(this));if(0>=--this.c)switch(this.f=(this.f+1)%6,this.c=ic(this),this.f){case 1:kc(this);break;case 2:kc(this);jc(this);break;case 3:kc(this);break;case 4:lc(this);break;case 5:kc(this);jc(this);lc(this);break;case 0:lc(this)}this.ea.w();this.fa.w();this.ha.w();this.da.w();this.Y.w();this.h&&0>=--this.m&&(this.m+=this.v/this.sampleRate,this.h(this.Z()))};
function kc(a){Zb(a.ea);Zb(a.fa);var b=a.ha;b.m?b.g=b.v:0<b.g&&b.g--;b.s||(b.m=!1);a=a.da;a.m?(a.m=!1,a.h=a.l,a.f=15):0<a.h?a.h--:(a.h=a.l,0<a.f?a.f--:a.L&&(a.f=15))}function jc(a){var b=a.ea;0<b.f&&!b.m&&b.f--;$b(b);b=a.fa;0<b.f&&!b.m&&b.f--;$b(b);b=a.ha;0<b.c&&!b.j&&b.c--;a=a.da;0<a.c&&!a.s&&a.c--}function lc(a){a.l||a.g||(a.j=!0,a=a.K,a.g|=4)}
c.Z=function(){var a=0,b=this.ea.Z(),d=this.fa.Z();if(b||d)a+=95.88/(8128/(b+d)+100);b=this.ha.Z();d=this.da.Z();var f=this.Y.Z();if(b||d||f)a+=159.79/(1/(b/8227+d/12241+f/22638)+100);return a};function mc(){var a=void 0===a?{}:a;A('Initializing NES');this.K=a.K||new Bb;this.u=a.u||new Ab;this.o=a.o||new fc;this.ca=a.ca||new Va;this.A=a.A||new Ba;this.C=a.C||new Qa;this.region=this.N=this.ja=null;this.K.connect(this);this.u.connect(this);this.o.connect(this);this.ca.connect(this);this.A.connect(this);nc(this)}c=mc.prototype;c.Tb=function(a){this.region=a;nc(this)};function oc(a){return a.region||a.ja&&a.ja.region||'NTSC'}
function nc(a){A('Updating region parameters');var b=oc(a),d=wa(b);A('Detected region: "'+b+'"');a.u.Sa(d);a.o.Sa(d)}function pc(a,b){a.ja&&(A('Removing current cartridge'),a.N.disconnect(),a.N=null,a.ja=null);if(b){A('Inserting cartridge');a.ja=b;var d=b.N,f=ob[d];if(f)A('Creating "'+d+'" mapper'),b=new f(b);else throw Error('Invalid mapper: '+n(d));a.N=b;a.N.connect(a);nc(a);a.Ob()}}
c.Ob=function(){this.ja&&(this.A.reset(),this.C.reset(),this.N.reset(),this.u.reset(),this.o.reset(),this.ca.reset(),this.K.reset())};c.reset=function(){var a=this.K;a.g|=1};c.xc=function(a,b){var d=this.A.Lb(a);d&&d.disconnect();this.A.xc(a,b);b&&b.connect(this)};c.Lb=function(a){return this.A.Lb(a)};
c.Sb=function(a){var b=this.u;A('Setting PPU base palette');b.Lc=a;for(a=0;a<b.zb.length;a++){var d=b.zb,f=a,h=b.Lc,l=a&6?.75:1,m=a&5?.75:1,p=a&3?.75:1;A('Creating palette variant ('+l+', '+m+', '+p+')');for(var r=new Uint32Array(64),q=0;64>q;q++){var G=e(vb(h[q])),R=G.next().value,I=G.next().value;G=G.next().value;R=Math.floor(l*R);I=Math.floor(m*I);G=Math.floor(p*G);r[q]=sb(R,I,G)}d[f]=r}b.ua=b.zb[b.Wb]};
c.pb=function(a){if(this.ja){var b=this.u;b.j=a;b.O=0;for(b.Kb=!1;!this.u.Kb;)this.K.step()}else for(b=0;b<a.length;b++){var d=~~(255*Math.random());a[b]=sb(d,d,d)}};c.vc=function(a){if(this.ja){var b=this.u;b.j=a;b.O=0;b.Kb=!1;this.u.vc()}else a.fill(wb)};c.qc=function(){return this.N?this.N.qc():null};function qc(){this.gb=new Uint8Array(24);this.gb[19]=1;this.c=0}qc.prototype.connect=function(){A('Connecting joypad')};qc.prototype.disconnect=function(){A('Disconnecting joypad')};qc.prototype.zc=function(){this.c=0};qc.prototype.read=function(){var a=this.gb[this.c];this.c=(this.c+1)%this.gb.length;return a};function rc(){this.Ac=!1;this.f=this.c=-1;this.u=null}rc.prototype.connect=function(a){A('Connecting zapper');this.u=a.u};rc.prototype.disconnect=function(){A('Disconnecting zapper');this.u=null};rc.prototype.zc=function(){};rc.prototype.read=function(){var a=this.Ac<<4,b;if(b=0<=this.c&&256>this.c&&0<=this.f&&240>this.f){b=this.u;var d=this.f;if(d<b.h-5||d>=b.h)b=!1;else{var f=e(vb(b.j[256*d+this.c]));b=f.next().value;d=f.next().value;f=f.next().value;b=18<b||18<d||18<f}}return a|!b<<3};var sc={},tc={0:'NROM',1:'MMC1',2:'UNROM',3:'CNROM',4:'MMC3',7:'AOROM',11:'COLOR_DREAMS',34:'BNROM'},uc={},vc=(uc[17]='SUROM',uc[18]='SOROM',uc[19]='SXROM',uc);function wc(a){return 78===a[0]&&69===a[1]&&83===a[2]&&26===a[3]}function xc(a){return 0<a?128*Math.pow(2,a-1):0}sc.name='iNES / NES 2.0';sc.supports=wc;
sc.parse=function(a){if(!wc(a))throw Error('Incorrect signature');if(16>a.length)throw Error('Input is too short: expected at least 16 B but got '+k(a.length));var b=a[4],d=a[5],f=a[7]&240|a[6]>>>4;var h=a[6]&8?'4S':a[6]&1?'V':'H';if(8===(a[7]&12)){A('Detected NES 2.0 format');var l=2;f|=(a[8]&15)<<8;var m=(a[8]&240)>>>4;b|=(a[9]&15)<<8;d|=(a[9]&240)<<4;var p=xc((a[10]&240)>>>4);var r=xc((a[11]&240)>>>4);var q=p+xc(a[10]&15);var G=r+xc(a[11]&15);var R=a[12]&1?'PAL':'NTSC'}else A('Detected iNES format'),
l=1,q=8192*(a[8]||1),p=a[6]&2?q:0,G=d?0:8192,r=0,R=a[9]&1?'PAL':'NTSC';if(0===b)throw Error('Invalid header: 0 PRG ROM units');var I=16+(a[6]&4?512:0);b*=16384;var M=I+b;d*=8192;var N=M+d,O=tc[f]||f.toString();'BNROM'===O&&0<d&&(O='NINA_001');f=vc[f<<4|m];if(a.length<N)throw Error('Input is too short: expected at least '+k(N)+' but got '+k(a.length));return{version:l,nb:h,region:R,N:O,me:f,ya:b,Ra:a.subarray(I,M),ob:q,Qb:p,Va:d,ib:d?a.subarray(M,N):void 0,hb:G,Jb:r}};var yc=[sc];var W='0123456789abcdef'.split(''),zc=[-2147483648,8388608,32768,128],Ac=[24,16,8,0];var Bc,Cc=window.AudioContext||window.webkitAudioContext;function Dc(a,b){var d=this;A('Initializing audio processor');this.c=a;this.i=b.createScriptProcessor(4096,0,1);this.i.onaudioprocess=function(a){a=a.outputBuffer;d.g||(d.h.fill(d.l,d.f),Ec(d));a.copyToChannel?a.copyToChannel(d.outputBuffer,0):a.getChannelData(0).set(d.outputBuffer);d.g=!1;d.c.o.qb(d.c.o.sampleRate+100*(.5-d.f/4096))};this.l=0;this.j=this.j.bind(this);this.f=0;this.h=new Float32Array(4096);this.outputBuffer=new Float32Array(4096);this.g=!1}
Dc.prototype.connect=function(a){A('Connecting audio processor');hc(this.c.o,this.j);this.i.connect(a)};Dc.prototype.disconnect=function(){A('Disconnecting audio processor');hc(this.c.o,null);this.i.disconnect()};Dc.prototype.qb=function(a){A('Setting sample rate to '+a+' Hz');this.c.o.qb(a)};Dc.prototype.j=function(a){if(4096===this.f){if(this.g)return;Ec(this)}this.l=this.h[this.f++]=a};function Ec(a){var b=e([a.h,a.outputBuffer]);a.outputBuffer=b.next().value;a.h=b.next().value;a.g=!0;a.f=0};var Fc={master:-1,pulse1:0,pulse2:1,triangle:2,noise:3,dmc:4};function Gc(a,b){A('Initializing audio mixer');this.f=a;this.volume=.5;this.c=b.createGain();this.c.connect(b.destination);this.c.gain.value=this.volume}Gc.prototype.Wa=function(){return this.c};Gc.prototype.sb=function(a,b){if('number'!==typeof b||0>b||1<b)throw Error('Invalid audio volume: '+n(b));this.Xa(a)!==b&&(A('Setting volume of "'+a+'" channel to '+~~(100*b)+'%'),a=Fc[a],0<=a?this.f.o.sb(a,b):(this.volume=b,this.c.gain.value=this.volume))};
Gc.prototype.Xa=function(a){var b=Fc[a];if(null==b)throw Error('Invalid audio channel: '+n(a));return 0<=b?this.f.o.Xa(b):this.volume};function Hc(a){A('Initializing audio');this.f=!0;this.h=!1;this.speed=1;null==Bc&&(Bc=new Cc);this.c=Bc;this.g=new Dc(a,this.c);this.i=new Gc(a,this.c);Ic(this);this.g.qb(this.c.sampleRate/this.speed)}c=Hc.prototype;c.fd=function(a){if('boolean'!==typeof a)throw Error('Invalid audio enabled: '+n(a));this.f!==a&&(A('Audio '+(a?'enabled':'disabled')),this.f=a,Ic(this))};c.ed=function(){return this.f};c.setActive=function(a){this.h!==a&&(A('Audio '+(a?'resumed':'suspended')),this.h=a,Ic(this))};
function Ic(a){a.f&&a.h?(a.g.connect(a.i.Wa()),a.c.resume()):a.g.disconnect()}c.rb=function(a){this.speed!==a&&(A('Setting audio speed to '+a+'x'),this.speed=a,this.g.qb(this.c.sampleRate/this.speed))};c.sb=function(a,b){this.i.sb(a,b)};c.Xa=function(a){return this.i.Xa(a)};var Jc=[1,2];function X(a,b){this.source=a;this.name=b}X.prototype.Na=function(a){return this.source===a.source&&this.name===a.name};X.prototype.toString=function(){return this.source+'.'+this.name};var Kc={65:'a',66:'b',67:'c',68:'d',69:'e',70:'f',71:'g',72:'h',73:'i',74:'j',75:'k',76:'l',77:'m',78:'n',79:'o',80:'p',81:'q',82:'r',83:'s',84:'t',85:'u',86:'v',87:'w',88:'x',89:'y',90:'z',48:'0',49:'1',50:'2',51:'3',52:'4',53:'5',54:'6',55:'7',56:'8',57:'9',32:'space',188:',',190:'.',191:'/',186:';',222:"'",220:'\\',219:'[',221:']',192:'`',189:'-',187:'=',112:'f1',113:'f2',114:'f3',115:'f4',116:'f5',117:'f6',118:'f7',119:'f8',120:'f9',121:'f10',122:'f11',123:'f12',16:'shift',17:'ctrl',18:'alt',
37:'left',38:'up',39:'right',40:'down',9:'tab',36:'home',35:'end',33:'page-up',34:'page-down',27:'escape',19:'pause',13:'enter',8:'backspace',45:'insert',46:'delete',20:'caps-lock',144:'num-lock',145:'scroll-lock',96:'numpad-0',97:'numpad-1',98:'numpad-2',99:'numpad-3',100:'numpad-4',101:'numpad-5',102:'numpad-6',103:'numpad-7',104:'numpad-8',105:'numpad-9',107:'add',109:'subtract',106:'multiply',111:'divide',110:'decimal-point'};
function Lc(a){var b=this;A('Initializing keyboard');this.g=a;this.c=function(a){return Mc(b,a,!0)};this.f=function(a){return Mc(b,a,!1)}}Lc.prototype.fc=function(){A('Activating keyboard');window.addEventListener('keydown',this.c);window.addEventListener('keyup',this.f)};Lc.prototype.mc=function(){A('Deactivating keyboard');window.removeEventListener('keydown',this.c);window.removeEventListener('keyup',this.f)};
function Mc(a,b,d){a.g.ga(new X('keyboard',Kc[b.keyCode||b.which]),d)&&b.preventDefault()};var Nc={0:'left',1:'middle',2:'right'};function Oc(a){var b=this;A('Initializing mouse');this.c=a;this.f=function(a){b.c.ga(new X('mouse',Nc[a.button]),!0)&&a.preventDefault()};this.h=function(a){b.c.ga(new X('mouse',Nc[a.button]),!1)&&a.preventDefault()};this.g=function(a){b.c.ga(new X('mouse','cursor'),[a.clientX,a.clientY])}}
Oc.prototype.fc=function(){A('Activating mouse');window.addEventListener('mousedown',this.f);window.addEventListener('mouseup',this.h);window.addEventListener('mousemove',this.g)};Oc.prototype.mc=function(){A('Deactivating mouse');window.removeEventListener('mousedown',this.f);window.removeEventListener('mouseup',this.h);window.removeEventListener('mousemove',this.g)};var Pc=['left-stick-x','left-stick-y','right-stick-x','right-stick-y'],Qc='a b x y left-bumper right-bumper left-trigger right-trigger back start left-stick right-stick dpad-up dpad-down dpad-left dpad-right guide'.split(' ');function Rc(a){A('Initializing gamepads');this.g=a;this.c=null;this.f=0}Rc.prototype.fc=function(){navigator.getGamepads?(A('Activating gamepads'),Sc(this)):Aa('Cannot activate gamepads (Gamepad API is not available)')};Rc.prototype.mc=function(){A('Deactivating gamepads');cancelAnimationFrame(this.f)};
function Sc(a){a.f=requestAnimationFrame(function(){var b=Tc();if(a.c)for(var d=a.c,f=0;f<d.length;f++){var h=d[f],l=b[f];if(h&&l){for(var m=h.axes,p=l.axes,r=0;r<Math.min(m.length,p.length);r++)if(m[r]!==p[r]){var q=a,G=r,R=m[r],I=p[r];R&&q.ga(l,Uc(l,G,R),!1);I&&q.ga(l,Uc(l,G,I),!0)}h=h.buttons;m=l.buttons;for(p=0;p<Math.min(h.length,m.length);p++)h[p]!==m[p]&&a.ga(l,'standard'===l.mapping?Qc[p]:'button-'+p,m[p])}}a.c=b;Sc(a)})}
function Tc(){return Array.from(navigator.getGamepads()).map(function(a){return a&&{index:a.index,mapping:a.mapping,axes:a.axes.map(Math.round),buttons:a.buttons.map(function(a){return a.pressed})}})}Rc.prototype.ga=function(a,b,d){this.g.ga(new X('gamepad'+a.index,b),d)};function Uc(a,b,d){d=0<d?'+':'-';return'standard'===a.mapping?Pc[b]+d:'axis-'+b+d};var Vc={},Wc=(Vc.keyboard={cc:Lc,rc:!1},Vc.mouse={cc:Oc,rc:!1},Vc.gamepad={cc:Rc,rc:!0},Vc);function Xc(a){A('Initializing sources');this.i=a;this.g=[];this.h=this.f=!1;this.c=null;for(var b in Wc)this.g.push(new Wc[b].cc(this))}Xc.prototype.setActive=function(a){this.f!==a&&(A('Sources '+(a?'activated':'deactivated')),a?this.g.forEach(function(a){return a.fc()}):this.g.forEach(function(a){return a.mc()}),this.f=a)};Xc.prototype.j=function(a){if('function'!==typeof a)throw Error('Invalid record input callback: '+n(a));A('Recording source input');this.c=a;this.h=this.f;this.setActive(!0)};
Xc.prototype.ga=function(a,b){return this.c?(b||(A('Caught "'+a+'" source input'),this.setActive(this.h),this.c(a.toString()),this.c=null),!0):this.i.ga(a,b)};function Yc(a,b,d){this.port=a;this.Ma=b;this.name=d}Yc.prototype.Na=function(a){return this.port===a.port&&this.Ma===a.Ma&&this.name===a.name};Yc.prototype.toString=function(){return this.port+'.'+this.Ma+'.'+this.name};var Zc={a:0,b:1,select:2,start:3,up:4,down:5,left:6,right:7};function $c(a){this.c=a}$c.prototype.Kc=function(){return this.c};$c.prototype.Za=function(a,b){if(a in Zc){if('boolean'!==typeof b)throw Error('Invalid joypad button state: '+n(b));this.c.gb[Zc[a]]=b?1:0}else throw Error('Invalid joypad button: '+n(a));};$c.prototype.Wa=function(a){if(a in Zc)return 1===this.c.gb[Zc[a]];throw Error('Invalid joypad button: '+n(a));};function ad(a){this.c=a}ad.prototype.Kc=function(){return this.c};
ad.prototype.Za=function(a,b){if('trigger'===a){if('boolean'!==typeof b)throw Error('Invalid zapper trigger state: '+n(b));this.c.Ac=b}else if('beam'===a){if(!Array.isArray(b)||2!==b.length)throw Error('Invalid zapper beam position: '+n(b));b=e(b);a=b.next().value;b=b.next().value;if('number'!==typeof a)throw Error('Invalid zapper beam X position: '+n(a));if('number'!==typeof b)throw Error('Invalid zapper beam Y position: '+n(b));var d=this.c;d.c=a;d.f=b}else throw Error('Invalid zapper input: '+
n(a));};ad.prototype.Wa=function(a){if('trigger'===a)return this.c.Ac;if('beam'===a)return a=this.c,[a.c,a.f];throw Error('Invalid zapper input: '+n(a));};var bd={},cd=(bd.joypad={Zb:qc,Dc:$c},bd.zapper={Zb:rc,Dc:ad},bd);function dd(a,b){if('string'===typeof a){if(null==b||b===X){var d=a.split('.');if(2!==d.length)d=null;else{var f=e(d);d=f.next().value;f=f.next().value;d=new X(d,f)}if(d){a=d.source;b=a.replace(/[0-9]+$/,'');f=Wc[b];if(!f||f.rc!==(a!==b))throw Error('Invalid input source: '+n(a));return d}}if(null==b||b===Yc){d=a.split('.');if(3!==d.length)d=null;else{var h=e(d);d=h.next().value;f=h.next().value;h=h.next().value;var l=parseInt(d,10);d=new Yc(isNaN(l)?d:l,f,h)}if(d){a=d.port;b=d.Ma;if(!(0<=Jc.indexOf(a)))throw Error('Invalid input port: '+
n(a));if(!(b in cd))throw Error('Invalid input device: '+n(b));return d}}}if(null!=b)throw Error('Invalid '+(b===X?'source':'device')+' input: '+n(a));throw Error('Invalid input: '+n(a));};function ed(a){A('Initializing devices');this.c=a;a={};for(var b=e(Jc),d=b.next();!d.done;d=b.next()){d=d.value;a[d]={};for(var f in cd){var h=cd[f];a[d][f]=new h.Dc(new h.Zb)}}this.fb=a;this.set(1,'joypad');this.set(2,'zapper')}ed.prototype.set=function(a,b){if(!(0<=Jc.indexOf(a)))throw Error('Invalid port: '+n(a));if(null!==b&&!(b in cd))throw Error('Invalid device: '+n(b));this.get(a)!==b&&(A('Setting device on port '+a+' to "'+(b||'none')+'"'),this.c.xc(a,null!==b?this.fb[a][b].Kc():null))};
ed.prototype.get=function(a){if(!(0<=Jc.indexOf(a)))throw Error('Invalid port: '+n(a));a=this.c.Lb(a);for(var b in cd)if(a instanceof cd[b].Zb)return b;return null};ed.prototype.Za=function(a,b){a=dd(a,Yc);this.fb[a.port][a.Ma].Za(a.name,b)};ed.prototype.Wa=function(a){a=dd(a,Yc);return this.fb[a.port][a.Ma].Wa(a.name)};function fd(){A('Initializing input map');this.c=[]}function gd(a,b){if(!b||'object'!==typeof b)throw Error('Invalid mapping: '+n(b));A('Unmapping all inputs');a.c.length=0;for(var d in b){var f=b[d];if('string'===typeof f)a.set(d,f);else if(Array.isArray(f)){f=e(f);for(var h=f.next();!h.done;h=f.next())a.set(d,h.value)}else throw Error('Invalid source input(s): '+n(f));}}c=fd.prototype;
c.set=function(a,b){a=dd(a,Yc);b=dd(b,X);this.has(a,b)||(A('Mapping "'+a+'" input to "'+b+'"'),this.c.push({jb:a,tb:b}))};c.get=function(a){var b=[];a=dd(a);this.forEach(a,function(a){b.push(a.toString())});return b};c.yd=function(a){var b=dd(a);A('Unmapping "'+b+'" input');this.c=this.c.filter(function(a){var d=a.tb;return!a.jb.Na(b)&&!d.Na(b)})};c.has=function(a,b){for(var d=e(this.c),f=d.next();!f.done;f=d.next())if(f=f.value,f.jb.Na(a)&&f.tb.Na(b))return!0;return!1};
c.forEach=function(a,b){if(a instanceof Yc)for(var d=e(this.c),f=d.next();!f.done;f=d.next())f=f.value,f.jb.Na(a)&&b(f.tb);else if(a instanceof X)for(d=e(this.c),f=d.next();!f.done;f=d.next())f=f.value,f.tb.Na(a)&&b(f.jb)};function hd(a,b,d){A('Initializing input router');this.map=a;this.f=b;this.video=d;this.c=null}
hd.prototype.ga=function(a,b){var d=this;if('mouse'===a.source){if(null==this.video.Z())return!1;if('cursor'===a.name){this.c=b;b=id(this.video,b[0],b[1]);a=e(Jc);for(var f=a.next();!f.done;f=a.next())this.f.fb[f.value].zapper.Za('beam',b);return!0}if(this.c){var h=e(this.c);f=h.next().value;h=h.next().value;var l=jd(this.video),m=l.top,p=l.bottom,r=l.right;if(f<l.left||f>r||h<m||h>p)return!1}}var q=!1;this.map.forEach(a,function(a){d.f.fb[a.port][a.Ma].Za(a.name,b);q=!0});return q};function kd(){this.index=this.time=0;this.c=Array(50).fill(0)}function ld(a){var b=void 0===b?window.performance.now():b;a.c[a.index]=b-a.time;a.index=(a.index+1)%a.c.length;a.time=b}kd.prototype.get=function(){return 1E3/(this.c.reduce(function(a,b){return a+b})/this.c.length)};var md={},nd=(md.auto=null,md.ntsc='NTSC',md.pal='PAL',md),od={setActive:function(){},rb:function(){}};
function pd(a,b,d,f){var h=this;A('Initializing system');this.c=a;this.video=b;this.audio=d||od;this.j=!1;this.f='auto';this.speed=1;this.h=this.g=0;this.i=f;this.l=new kd;this.c.Tb(nd[this.f]);this.audio.rb(this.speed);'https:'===location.protocol&&document.addEventListener('visibilitychange',function(){document.hidden?(A('Lost visibility'),h.j=h.Oa(),h.eb()):(A('Gained visibility'),h.j&&h.start())})}c=pd.prototype;
c.start=function(){var a=this;if(!this.Oa()){A('Starting execution');var b=1E3/(this.speed*wa(oc(this.c)).pc);this.g=setInterval(function(){return a.step()},b);this.audio.setActive(!0);this.i.setActive(!0)}};c.eb=function(){this.Oa()&&(A('Stopping execution'),clearInterval(this.g),cancelAnimationFrame(this.h),this.g=0,this.audio.setActive(!1),this.i.setActive(!1))};c.Oa=function(){return!!this.g};
c.step=function(){var a=this;this.video.Z()&&(this.video.pb(),cancelAnimationFrame(this.h),this.h=requestAnimationFrame(function(){return a.video.aa()}));ld(this.l)};c.Ob=function(){A('HW reset');this.c.Ob()};c.reset=function(){A('SW reset');this.c.reset()};c.Tb=function(a){if(!(a in nd))throw Error('Invalid region: '+n(a));this.f!==a&&(A('Setting region to "'+a+'"'),this.f=a,this.c.Tb(nd[this.f]),this.Oa()&&(this.eb(),this.start()))};c.Md=function(){return this.f};
c.rb=function(a){if('number'!==typeof a||0>=a)throw Error('Invalid speed: '+n(a));this.speed!==a&&(A('Setting emulation speed to '+a+'x'),this.speed=a,this.audio.rb(this.speed),this.Oa()&&(this.eb(),this.start()))};c.Nd=function(){return this.speed};c.be=function(){return this.l.get()};var qd=['maximized','normalized','stretched'],rd={position:'fixed',top:'0',right:'0',bottom:'0',left:'0',margin:'auto',width:'auto',height:'auto'};var sd;function td(){if(null==sd){A('Creating auxiliary canvas');var a=document.createElement('canvas');a.width=256;a.height=240;sd=ud(a)}return sd}function ud(a){A('Getting 2d canvas context');a=a.getContext('2d',{alpha:!1});if(null==a)throw Error('Unable to get 2d canvas context');return a}function vd(a){this.c=ud(a);this.g='nearest';this.f=1}c=vd.prototype;c.kc=function(a,b,d,f){d=this.c.createImageData(d,f);f=(new Uint32Array(d.data.buffer)).fill(wb);return{x:a,y:b,data:f,ge:d}};
c.aa=function(a){(1!==this.f?td():this.c).putImageData(a.ge,a.x,a.y)};c.Gc=function(){};c.end=function(){if(1!==this.f){var a='linear'===this.g;this.c.imageSmoothingEnabled=a;this.c.mozImageSmoothingEnabled=a;this.c.oImageSmoothingEnabled=a;this.c.msImageSmoothingEnabled=a;a=td().canvas;var b=this.c.canvas;this.c.drawImage(a,0,0,a.width,a.height,0,0,b.width,b.height)}};c.Rb=function(a){this.g=a};c.Ub=function(a){this.f=a};function wd(a,b,d){b=a.createShader(b);a.shaderSource(b,d);a.compileShader(b);if(!a.getShaderParameter(b,a.COMPILE_STATUS))throw Error('Shader compilation error: '+a.getShaderInfoLog(b));return b}
function xd(a){a:{for(var b={alpha:!1,depth:!1,antialias:!1},d=e(['webgl','experimental-webgl']),f=d.next();!f.done;f=d.next())if(f=f.value,A('Getting '+f+' canvas context'),f=a.getContext(f,b))break a;throw Error('Unable to get webgl or experimental-webgl canvas context');}a=f;b=a.createProgram();a.attachShader(b,wd(a,a.VERTEX_SHADER,'\n  uniform vec2 uScreenSize;\n  attribute vec2 aVertexPosition;\n  attribute vec2 aTextureCoord;\n  varying vec2 vTextureCoord;\n\n  void main(void) {\n    float x = aVertexPosition.x / (0.5 * uScreenSize.x) - 1.0; // [0, width] -> [-1, 1]\n    float y = 1.0 - aVertexPosition.y / (0.5 * uScreenSize.y); // [height, 0] -> [-1, 1]\n    gl_Position = vec4(x, y, 0.0, 1.0);\n    vTextureCoord = aTextureCoord;\n  }\n'));
a.attachShader(b,wd(a,a.FRAGMENT_SHADER,'\n  precision mediump float;\n\n  uniform sampler2D uSampler;\n  varying vec2 vTextureCoord;\n\n  void main(void) {\n    gl_FragColor = texture2D(uSampler, vTextureCoord);\n  }\n'));a.linkProgram(b);if(!a.getProgramParameter(b,a.LINK_STATUS))throw Error('Shader linking error');d=a.getUniformLocation(b,'uScreenSize');f=a.getUniformLocation(b,'uSampler');var h=a.getAttribLocation(b,'aVertexPosition'),l=a.getAttribLocation(b,'aTextureCoord');a.enableVertexAttribArray(h);
a.enableVertexAttribArray(l);a.useProgram(b);this.c=a;this.f=1;this.g='nearest';this.i=d;this.h=f;this.l=h;this.j=l}c=xd.prototype;
c.kc=function(a,b,d,f){d=yd(d);f=yd(f);var h=this.c,l=(new Uint32Array(d*f)).fill(wb),m=this.c;b=new Float32Array([a,b,a+d,b,a+d,b+f,a,b+f]);a=m.createBuffer();m.bindBuffer(m.ARRAY_BUFFER,a);m.bufferData(m.ARRAY_BUFFER,b,m.STATIC_DRAW);m=this.c;b=new Float32Array([0,0,1,0,1,1,0,1]);var p=m.createBuffer();m.bindBuffer(m.ARRAY_BUFFER,p);m.bufferData(m.ARRAY_BUFFER,b,m.STATIC_DRAW);return{width:d,height:f,data:l,$c:a,coords:p,ne:h.createTexture()}};
c.aa=function(a){var b=this.c,d='linear'===this.g?b.LINEAR:b.NEAREST,f=new Uint8Array(a.data.buffer);b.activeTexture(b.TEXTURE0);b.bindTexture(b.TEXTURE_2D,a.ne);b.texParameteri(b.TEXTURE_2D,b.TEXTURE_MAG_FILTER,d);b.texParameteri(b.TEXTURE_2D,b.TEXTURE_MIN_FILTER,d);b.texImage2D(b.TEXTURE_2D,0,b.RGBA,a.width,a.height,0,b.RGBA,b.UNSIGNED_BYTE,f);b=this.c;b.uniform1i(this.h,0);b.bindBuffer(b.ARRAY_BUFFER,a.$c);b.vertexAttribPointer(this.l,2,b.FLOAT,!1,0,0);b.bindBuffer(b.ARRAY_BUFFER,a.coords);b.vertexAttribPointer(this.j,
2,b.FLOAT,!1,0,0);b=this.c;b.bindBuffer(b.ARRAY_BUFFER,a.$c);b.drawArrays(b.TRIANGLE_FAN,0,4)};c.Gc=function(){var a=this.c,b=a.canvas,d=b.width;b=b.height;var f=d/this.f,h=b/this.f;a.viewport(0,0,d,b);a.clearColor(0,0,0,1);a.clear(a.COLOR_BUFFER_BIT);a.uniform2f(this.i,f,h)};c.end=function(){this.c.flush()};c.Ub=function(a){this.f=a};c.Rb=function(a){this.g=a};function yd(a){for(var b=1;b<a;)b*=2;return b};var zd={},Ad=(zd.canvas=vd,zd.webgl=xd,zd),Bd={},Cd=(Bd.webgl='canvas',Bd);for(var Dd=null,Ed=e(['','webkit','moz','ms']),Fd=Ed.next();!Fd.done;Fd=Ed.next()){var Gd=Fd.value;if(Hd('fullscreenElement',Gd)in document){Dd=Gd;break}}function Hd(a,b){b=void 0===b?Dd:b;'moz'===b&&(a=a.replace('exit','cancel').replace('screen','Screen'));return b+(a.charAt(0).toUpperCase()+a.slice(1))}
function Id(){var a=this;this.c=null;Jd('change',function(){var b=a.is()?'enter':'exit';A('Fullscreen '+b+'ed');a.c&&a.c.type===b&&(a.c.resolve(),a.c=null)});Jd('error',function(){y.error('Detected fullscreen error');a.c&&(a.c.reject(Error('Failed to '+a.c.type+' fullscreen')),a.c=null)})}Id.prototype.is=function(){return null!=Dd?null!=document[Hd('fullscreenElement')]:!1};
function Jd(a,b){null!=Dd&&document.addEventListener('ms'===Dd?'MSFullscreen'+(a.charAt(0).toUpperCase()+a.slice(1)):Dd+'fullscreen'+a,b)}
Id.prototype.f=function(a){var b=this;A('Fullscreen enter requested');if(null==Dd)return Promise.reject(Error('Browser does not support fullscreen API'));if(null==Dd||!document[Hd('fullscreenEnabled')])return Promise.reject(Error('Browser is blocking fullscreen request'));if(this.is())return Promise.resolve();if(this.c&&'exit'===this.c.type)return Promise.reject(Error('Fullscreen exit in progress'));null==this.c&&(this.c={type:'enter'},this.c.tc=new Promise(function(d,f){A('Entering fullscreen');
b.c.resolve=d;b.c.reject=f;a[Hd('requestFullscreen')]()}));return this.c.tc};Id.prototype.g=function(){var a=this;A('Fullscreen exit requested');if(!this.is())return Promise.resolve();if(this.c&&'enter'===this.c.type)return Promise.reject(Error('Fullscreen enter in progress'));null==this.c&&(this.c={type:'exit'},this.c.tc=new Promise(function(b,d){A('Exiting fullscreen');a.c.resolve=b;a.c.reject=d;document[Hd('exitFullscreen')]()}));return this.c.tc};function Kd(a){var b=this;A('Initializing video');this.j=a;this.f=this.canvas=null;this.v='webgl';this.g='fceux';this.m=this.i=null;this.l=1;this.h='nearest';this.c=!1;this.s='maximized';this.L=new Id;Jd('change',function(){b.canvas&&(A('Updating canvas after fullscreen change'),Ld(b),Md(b),Nd(b),b.aa())});this.j.Sb(yb(this.g));'https:'===location.protocol&&window.addEventListener('deviceorientation',function(){return Od(b)});window.addEventListener('resize',function(){return Od(b)})}
function Od(a){a.mb()&&(A('Updating fullscreen canvas after resolution change'),Ld(a),Md(a),Nd(a),a.aa())}c=Kd.prototype;
c.yc=function(a){if(null!==a&&!(a instanceof HTMLCanvasElement))throw Error('Invalid video output: '+n(a));A('Setting video output to '+a);if(this.canvas=a){a:{a=this.v;var b=this.canvas;do{var d=Ad[a];if(null==d)throw Error('Invalid renderer: '+n(a));try{A('Creating "'+a+'" renderer');var f=new d(b);break a}catch(h){y.error('Failed to create "'+a+'" renderer',h)}a=Cd[a]}while(a);throw Error('Unable to create renderer');}this.f=f;this.i=this.f.kc(0,0,256,240);this.m=this.f.kc(256,0,256,240);Ld(this);
Md(this);Nd(this);this.aa()}};c.Z=function(){return this.canvas};function jd(a){return a.canvas?a.canvas.getBoundingClientRect():null}function id(a,b,d){if(a.canvas){var f=jd(a);return[~~((b-f.left)/(f.width/(256*(a.c?2:1)))),~~((d-f.top)/(f.height/240))]}return null}function Md(a){a.canvas.width=256*Pd(a)*(a.c?2:1);a.canvas.height=240*Pd(a);A('Canvas resized to '+a.canvas.width+'x'+a.canvas.height+' px')}
function Nd(a){if(a.mb()){var b=a.canvas;a=a.s;A('Applying "'+a+'" style to canvas');var d=Object.assign(b.style,rd);'maximized'===a?b.width/b.height>window.innerWidth/window.innerHeight?d.width='100%':d.height='100%':'stretched'===a&&(d.width='100%',d.height='100%')}else for(b in a=a.canvas,A('Removing style from canvas'),a=a.style,rd)a.removeProperty(b)}
c.le=function(a){if(!(a in Ad))throw Error('Invalid video renderer: '+n(a));if(this.v!==a){if(this.canvas)throw Error('Cannot change video renderer once output is set');A('Using "'+a+'" video renderer');this.v=a}};c.ee=function(){return this.v};function Ld(a){a.f.Rb(a.h);a.f.Ub(Pd(a))}c.pb=function(){this.j.pb(this.i.data);this.c&&this.j.vc(this.m.data)};c.aa=function(){this.f.Gc();this.f.aa(this.i);this.c&&this.f.aa(this.m);this.f.end()};
c.Zd=function(){if(null==this.canvas)throw Error('No video output');this.i.data.fill(wb);this.c&&this.m.data.fill(wb);this.aa()};c.Sb=function(a){if(!(a in xb))throw Error('Invalid video palette: '+n(a));this.g!==a&&(A('Setting video palette to "'+a+'"'),this.g=a,this.j.Sb(yb(this.g)),this.canvas&&(this.pb(),this.aa()))};c.Wd=function(){return this.g};
c.Ub=function(a){if('number'!==typeof a||0>=a)throw Error('Invalid video scale: '+n(a));this.l!==a&&(A('Setting video scale to '+a),this.l=a,this.canvas&&(Ld(this),Md(this),Nd(this),this.aa()))};c.fe=function(){return this.l};function Pd(a){a.mb()?(a=Math.min(window.innerWidth/(256*(a.c?2:1)),window.innerHeight/240),a=1<a?~~a:a):a=a.l;return a}
c.Rb=function(a){if(!(0<=['nearest','linear'].indexOf(a)))throw Error('Invalid video filter: '+n(a));this.h!==a&&(A('Setting video filter to "'+a+'"'),this.h=a,this.canvas&&(Ld(this),this.aa()))};c.ce=function(){return this.h};c.je=function(a){if('boolean'!==typeof a)throw Error('Invalid video debug: '+n(a));this.c!==a&&(A('Setting video debug to '+(a?'on':'off')),this.c=a,this.canvas&&(Ld(this),Md(this),Nd(this),this.pb(),this.aa()))};c.ie=function(){return this.c};
c.ae=function(){if(null==this.canvas)throw Error('No video output');return this.L.f(this.canvas.parentElement)};c.Vd=function(){return this.L.g()};c.mb=function(){return this.L.is()};c.ke=function(a){if(!(0<=qd.indexOf(a)))throw Error('Invalid fullscreen type: '+n(a));this.s!==a&&(A('Setting fullscreen type to "'+a+'"'),this.s=a,this.mb()&&Nd(this))};c.de=function(){return this.s};function Qd(a){A('Downloading data from "'+a+'"');return new Promise(function(b,d){var f=new XMLHttpRequest;f.open('GET',a,!0);f.responseType='arraybuffer';f.onload=function(){200===f.status?b(f.response):0===f.status?d(Error('Failed to connect to the server')):d(Error('Failed to download data ('+f.status+' '+f.statusText+')'))};f.onerror=function(){d(Error('Failed to connect to the server'))};f.send()})}
function Rd(a){A('Reading contents of '+k(a.size)+' blob');return new Promise(function(b,d){if(10485760<a.size)d(Error('Input is too large ('+k(a.size)+')'));else{var f=new FileReader;f.onload=function(a){b(a.target.result)};f.onerror=function(a){d(Error(a.target.error||'Unknown error'))};f.readAsArrayBuffer(a)}})};function Sd(a,b,d){A('Initializing ROM loader');this.c=a;this.g=b;this.h=d}Sd.prototype.load=function(a){var b=this;if('string'===typeof a)return Qd(a).then(function(a){return Td(b,a)});if(a instanceof Blob)return Rd(a).then(function(a){return Td(b,a)});if(a instanceof Array||a instanceof ArrayBuffer||a instanceof Uint8Array)return Td(this,a);throw Error('Invalid source: '+n(a));};
function Td(a,b){b instanceof Uint8Array||(b=new Uint8Array(b));return Ud(a,b).then(function(b){a:{A('Creating cartridge from ROM image');if(!(b instanceof Uint8Array))throw Error('Invalid ROM image: '+n(b));A('Parsing '+k(b.length)+' of data');for(var d=e(yc),h=d.next();!h.done;h=d.next())if(h=h.value,h.supports(b)){A('Using "'+h.name+'" parser');b=h.parse(b);var l;A('Computing SHA-1');d=new Uint8Array(b.ya+b.Va);d.set(b.Ra);b.ib&&d.set(b.ib,b.ya);h=d.length;var m=Array(17),p=0,r=0,q=0,G=0,R=!1,
I=1732584193,M=4023233417,N=2562383102,O=271733878,V=3285377520;do{m[0]=p;m.fill(0,1,17);for(l=q;r<h&&64>l;r++)m[l>>2]|=d[r]<<Ac[l++&3];G+=l-q;q=l-64;r===h&&(m[l>>2]|=zc[l&3],r++);p=m[16];r>h&&56>l&&(m[15]=G<<3,R=!0);for(l=16;80>l;l++){var z=m[l-3]^m[l-8]^m[l-14]^m[l-16];m[l]=z<<1|z>>>31}var t=I,u=M,v=N,w=O,x=V;for(l=0;20>l;l+=5){var C=u&v|~u&w;z=t<<5|t>>>27;x=z+C+x+1518500249+m[l]<<0;u=u<<30|u>>>2;C=t&u|~t&v;z=x<<5|x>>>27;w=z+C+w+1518500249+m[l+1]<<0;t=t<<30|t>>>2;C=x&t|~x&u;z=w<<5|w>>>27;v=z+C+
v+1518500249+m[l+2]<<0;x=x<<30|x>>>2;C=w&x|~w&t;z=v<<5|v>>>27;u=z+C+u+1518500249+m[l+3]<<0;w=w<<30|w>>>2;C=v&w|~v&x;z=u<<5|u>>>27;t=z+C+t+1518500249+m[l+4]<<0;v=v<<30|v>>>2}for(;40>l;l+=5)C=u^v^w,z=t<<5|t>>>27,x=z+C+x+1859775393+m[l]<<0,u=u<<30|u>>>2,C=t^u^v,z=x<<5|x>>>27,w=z+C+w+1859775393+m[l+1]<<0,t=t<<30|t>>>2,C=x^t^u,z=w<<5|w>>>27,v=z+C+v+1859775393+m[l+2]<<0,x=x<<30|x>>>2,C=w^x^t,z=v<<5|v>>>27,u=z+C+u+1859775393+m[l+3]<<0,w=w<<30|w>>>2,C=v^w^x,z=u<<5|u>>>27,t=z+C+t+1859775393+m[l+4]<<0,v=v<<
30|v>>>2;for(;60>l;l+=5)C=u&v|u&w|v&w,z=t<<5|t>>>27,x=z+C+x-1894007588+m[l]<<0,u=u<<30|u>>>2,C=t&u|t&v|u&v,z=x<<5|x>>>27,w=z+C+w-1894007588+m[l+1]<<0,t=t<<30|t>>>2,C=x&t|x&u|t&u,z=w<<5|w>>>27,v=z+C+v-1894007588+m[l+2]<<0,x=x<<30|x>>>2,C=w&x|w&t|x&t,z=v<<5|v>>>27,u=z+C+u-1894007588+m[l+3]<<0,w=w<<30|w>>>2,C=v&w|v&x|w&x,z=u<<5|u>>>27,t=z+C+t-1894007588+m[l+4]<<0,v=v<<30|v>>>2;for(;80>l;l+=5)C=u^v^w,z=t<<5|t>>>27,x=z+C+x-899497514+m[l]<<0,u=u<<30|u>>>2,C=t^u^v,z=x<<5|x>>>27,w=z+C+w-899497514+m[l+1]<<
0,t=t<<30|t>>>2,C=x^t^u,z=w<<5|w>>>27,v=z+C+v-899497514+m[l+2]<<0,x=x<<30|x>>>2,C=w^x^t,z=v<<5|v>>>27,u=z+C+u-899497514+m[l+3]<<0,w=w<<30|w>>>2,C=v^w^x,z=u<<5|u>>>27,t=z+C+t-899497514+m[l+4]<<0,v=v<<30|v>>>2;I=I+t<<0;M=M+u<<0;N=N+v<<0;O=O+w<<0;V=V+x<<0}while(!R);b.Zc=W[I>>28&15]+W[I>>24&15]+W[I>>20&15]+W[I>>16&15]+W[I>>12&15]+W[I>>8&15]+W[I>>4&15]+W[I&15]+W[M>>28&15]+W[M>>24&15]+W[M>>20&15]+W[M>>16&15]+W[M>>12&15]+W[M>>8&15]+W[M>>4&15]+W[M&15]+W[N>>28&15]+W[N>>24&15]+W[N>>20&15]+W[N>>16&15]+W[N>>
12&15]+W[N>>8&15]+W[N>>4&15]+W[N&15]+W[O>>28&15]+W[O>>24&15]+W[O>>20&15]+W[O>>16&15]+W[O>>12&15]+W[O>>8&15]+W[O>>4&15]+W[O&15]+W[V>>28&15]+W[V>>24&15]+W[V>>20&15]+W[V>>16&15]+W[V>>12&15]+W[V>>8&15]+W[V>>4&15]+W[V&15];A('==========[Cartridge Info - Start]==========');A('SHA-1                 : '+b.Zc);A('Mapper                : '+b.N);A('Submapper             : '+b.me);A('Region                : '+b.region);A('Mirroring             : '+b.nb);A('PRG ROM size          : '+k(b.ya));A('PRG RAM size          : '+
k(b.ob));A('PRG RAM size (battery): '+k(b.Qb));A('CHR ROM size          : '+k(b.Va));A('CHR RAM size          : '+k(b.hb));A('CHR RAM size (battery): '+k(b.Jb));A('==========[Cartridge Info - End]==========');break a}throw Error('Unknown ROM image format');}pc(a.c,b);a.g.Oa()&&(b=a.g,b.eb(),b.start())})}
function Ud(a,b){if(80===b[0]&&75===b[1]&&3===b[2]&&4===b[3]){A('Extracting ROM image from '+k(b.length)+' ZIP archive');a=a.h;if(null==a||null==a.loadAsync)throw Error('Unable to extract ROM image: JSZip 3 is not available');return a.loadAsync(b).then(function(a){a=a.file(/^.*\.nes$/i);if(0===a.length)throw Error('ZIP archive does not contain ".nes" ROM image');return a[0].async('uint8array')})}return Promise.resolve(b)}Sd.prototype.j=function(){this.f()&&(A('Unloading ROM image'),pc(this.c,null))};
Sd.prototype.f=function(){return null!=this.c.ja};Sd.prototype.i=function(){var a=this.c.ja;return a?a.Zc:null};function Vd(a){var b={},d;for(d in a){var f=Object.getOwnPropertyDescriptor(a,d);if(f.enumerable){var h=a[d];f.writable||f.set?b[d]=h:'object'===typeof h&&(b[d]=Vd(h))}}return b};function Wd(a,b){for(var d in b)if(d in a){var f=b[d];if(void 0!==f){var h=Object.getOwnPropertyDescriptor(a,d);h.enumerable&&(h.writable||h.set?a[d]=f:'object'===typeof f&&Wd(a[d],f))}}};function Xd(a,b){for(var d=[],f=1;f<arguments.length;++f)d[f-1]=arguments[f];return{get:Yd.apply(null,[].concat([a],pa(d)))}}function Y(a,b,d){for(var f=[],h=2;h<arguments.length;++h)f[h-2]=arguments[h];return{get:Yd.apply(null,[].concat([a],pa(f))),set:Yd.apply(null,[].concat([b],pa(f))),enumerable:!0}}function Zd(a,b,d){for(var f=[],h=2;h<arguments.length;++h)f[h-2]=arguments[h];return{get:Yd.apply(null,[].concat([a],pa(f))),set:Yd.apply(null,[].concat([b],pa(f)))}}
function Z(a,b){for(var d=[],f=1;f<arguments.length;++f)d[f-1]=arguments[f];return{value:Yd.apply(null,[].concat([a],pa(d)))}}function $d(a){return{value:Object.defineProperties({},a),enumerable:!0}}function ae(a,b,d,f){for(var h=[],l=3;l<arguments.length;++l)h[l-3]=arguments[l];l=e(h);h=l.next().value;l=ia(l);for(var m={},p=e(a),r=p.next();!r.done;r=p.next())r=r.value,m[r]=Y.apply(null,[].concat([b,d,h,r],pa(l)));return $d(m)}
function Yd(a,b){for(var d=[],f=1;f<arguments.length;++f)d[f-1]=arguments[f];return d.length?a.bind.apply(a,[].concat(pa(d))):a};var be=Object.defineProperties;
function ce(a){function b(a){Wd(G,a);'inputs'in a&&gd(p,a.inputs)}a=void 0===a?{}:a;if(!a||'object'!==typeof a)throw Error('Invalid initialization options: '+n(a));var d=a.JSZip||window.JSZip,f=new mc,h=new Kd(f),l=null!=Cc?new Hc(f):null,m=new ed(f),p=new fd,r=new hd(p,m,h);r=new Xc(r);var q=new pd(f,h,l,r);d=new Sd(f,q,d);var G=be({},{running:Xd(q.Oa,q),fps:Xd(q.be,q),region:Y(q.Md,q.Tb,q),speed:Y(q.Nd,q.rb,q),start:Z(q.start,q),stop:Z(q.eb,q),step:Z(q.step,q),power:Z(q.Ob,q),reset:Z(q.reset,q),
nvram:Xd(f.qc,f),use:Z(b),rom:$d({loaded:Xd(d.f,d),sha1:Xd(d.i,d),load:Z(d.load,d),unload:Z(d.j,d)}),video:$d({output:Zd(h.Z,h.yc,h),renderer:Y(h.ee,h.le,h),palette:Y(h.Wd,h.Sb,h),scale:Y(h.fe,h.Ub,h),filter:Y(h.ce,h.Rb,h),debug:Y(h.ie,h.je,h),clear:Z(h.Zd,h)}),fullscreen:$d({type:Y(h.de,h.ke,h),is:Xd(h.mb,h),enter:Z(h.ae,h),exit:Z(h.Vd,h)}),audio:l?$d({enabled:Y(l.ed,l.fd,l),volume:ae(Object.keys(Fc),l.Xa,l.sb,l)}):{value:null},devices:ae(Jc,m.get,m.set,m),inputs:$d({state:$d({get:Z(m.Wa,m),set:Z(m.Za,
m)}),map:$d({get:Z(p.get,p),set:Z(p.set,p),'delete':Z(p.yd,p)}),record:Z(r.j,r)}),config:$d({get:Z(function(){for(var a=Vd(G),b={},d=e(p.c),f=d.next();!f.done;f=d.next()){var h=f.value;f=h.jb.toString();h=h.tb.toString();b[f]=b[f]||[];b[f].push(h)}a.inputs=b;return a}),use:Z(b)}),toString:Z(function(){return'cfxnes 0.7.0'})});b(a);(f=a.video)&&'output'in f?h.yc(f.output):(f=document.getElementById('cfxnes'),f instanceof HTMLCanvasElement&&h.yc(f));'inputs'in a||gd(p,{'1.joypad.a':'keyboard.x','1.joypad.b':['keyboard.y',
'keyboard.z'],'1.joypad.start':'keyboard.enter','1.joypad.select':'keyboard.shift','1.joypad.up':'keyboard.up','1.joypad.down':'keyboard.down','1.joypad.left':'keyboard.left','1.joypad.right':'keyboard.right','2.zapper.trigger':'mouse.left'});'rom'in a&&d.load(a.rom).then(function(){return q.start()}).catch(function(a){y.error('Failed to load ROM',a)});return G}y.h('warn');try{be(ce,{name:{value:'cfxnes'}})}catch(a){Aa('Unable to redefine cfxnes.name property: running in pre-ES2015 environment')}
be(ce,{version:{value:'0.7.0'},logLevel:Y(y.i,y.h,y),close:{value:function(){if(null==Bc)return Promise.resolve();var a=Bc.close();Bc=void 0;return a}}});'undefined'!==typeof root&&(root.cfxnes=ce);
  // Compiler output [end]
  return root;
}.bind(this)));

//# sourceMappingURL=cfxnes.js.map
